import { relative } from 'path';
import { formatItem, formatSection, warnSymbol } from '@teambit/cli';

const SKIPPED_DESCRIPTION = `these files already exist and were not generated by bit, so they were left untouched.
to have bit write them, delete them first or run "bit ws-config write --force".`;

/**
 * config files that bit wanted to write but are authored by the user.
 * returns an empty string when nothing was skipped.
 */
export function formatSkippedOutput(skippedPaths: string[], wsDir: string): string {
  const items = skippedPaths.map((path) => formatItem(relative(wsDir, path)));
  return formatSection(`${warnSymbol} config files not overridden`, SKIPPED_DESCRIPTION, items);
}
