/**
 * compiler that supports the capsule interface.
 * do nothing to the source code, just replace ";" with ";\n".
 */
const path = require('path');
const os = require('os');

function compile(files, distPath, context) {
  const targetDir = path.join(os.tmpdir(), generateRandomStr());
  const distSignature = '// THIS IS A DIST FILE GENERATED BY A DUMMY COMPILER\n';
  return context.isolate({ targetDir }).then(({ capsule, componentWithDependencies }) => {
    const componentRootDir = path.join(targetDir, componentWithDependencies.component.writtenPath);
    return files
      .map((file) => {
        const distFile = file.clone();
        const content = distSignature + file.contents.toString().replace(/;/g, ";\n");
        distFile.base = distPath;
        distFile.path = path.join(distPath, file.relative);
        distFile.contents = Buffer.from(content);
        return distFile;
      });
  });
}

function generateRandomStr(size = 8) {
  return Math.random()
    .toString(36)
    .slice(size * -1);
}

module.exports = {
  compile
};
