// Sources deliberately remain inline: invalid syntax and unsupported modes are test inputs.
module.exports = [
  { name: 'empty', path: 'empty.js', source: '' },
  { name: 'imports', path: 'imports.js', source: `import main, { original as local } from 'pkg'; import * as ns from './ns'; import './side'; export { local }; export default main;` },
  { name: 'reexports-js', path: 'exports.mjs', source: `export { default as renamed, value as alias } from './one'; export * from './two';` },
  { name: 'calls', path: 'calls.cjs', source: `const a = require('pkg'); require.resolve('./resolved'); import('./dynamic'); require(variable); import(variable);` },
  { name: 'unclassified-js', path: 'resolve-only.js', source: `const target = require.resolve('./resolved');` },
  { name: 'duplicates', path: 'duplicates.js', source: `import { a } from 'pkg'; import { b } from 'pkg'; require('pkg');` },
  { name: 'comments-strings', path: 'comments.js', source: `// require('fake')\nconst text = "import x from 'fake'"; import './real';` },
  { name: 'jsx', path: 'view.jsx', source: `import React from 'react'; import View from './view'; const x = <View />;` },
  { name: 'typescript', path: 'types.ts', source: `import type { A as B } from 'types'; import { C } from './runtime'; export type { D } from './exported'; import E = require('./external');` },
  { name: 'tsx', path: 'view.tsx', source: `import View from './view'; const x: JSX.Element = <View />;` },
  { name: 'mts', path: 'module.mts', source: `import type { A } from './a'; export * from './b';` },
  { name: 'cts', path: 'module.cts', source: `import x = require('./a');` },
  { name: 'type-overwrite', path: 'duplicates.ts', source: `import type { A } from 'pkg'; import { B } from 'pkg';` },
  { name: 'ignore-line', path: 'ignore.ts', source: `// @bit-ignore\nimport x from './ignored';\nimport y from './included';` },
  { name: 'no-check-ts', path: 'skip.ts', source: `import x from './first';\n// @bit-no-check\nimport y from './second';` },
  { name: 'no-check-js', path: 'skip.js', source: `// @bit-no-check\nimport x from './ignored';` },
  { name: 'no-check-invalid-js', path: 'skip-invalid.js', source: `/* @bit-no-check */\nconst = invalid;` },
  { name: 'escaped-specifier', path: 'escaped.js', source: `import './\\u0061'; require('./\\u0062');` },
  { name: 'literal-templates', path: 'templates.ts', source: 'require(`./template`); import(`./dynamic`); require(`./${variable}`);' },
  { name: 'core-filter', path: 'core.js', source: `import fs from 'fs'; import path from 'node:path'; import x from 'pkg';`, options: { includeCore: false }, expectFallback: 'Nonempty options retain legacy filtering' },
  { name: 'angular', path: 'angular.ts', source: `@Component({ templateUrl: 'view.html', styleUrl: './view.css', styleUrls: ['one.css', '../two.css'] }) class View {}`, expectFallback: 'Decorator asset extraction retains the legacy detector' },
  { name: 'invalid-js', path: 'invalid.js', source: `import { from 'pkg';` },
  { name: 'invalid-ts', path: 'invalid.ts', source: `const value: = 1;` },
  { name: 'amd', path: 'amd.js', source: `define(['pkg'], function(pkg) {});`, fallback: 'AMD dispatch remains on the legacy detector' },
  { name: 'custom-detector', path: 'custom.js', source: `import x from 'pkg';`, options: { customDetector: true }, fallback: 'Environment and global detectors take precedence' },
  { name: 'unsupported-css', path: 'style.css', source: `@import './other.css';`, fallback: 'Non-JS/TS detectors remain on the legacy path' },
];
