import { expect } from 'chai';
import { ABSENT_ON_BRANCH, branchStateFingerprint, fingerprintIdVersions, parseBranchBitmap } from './bitmap-state';

const DEFAULT_SCOPE = 'acme.shop';
const SNAP_1 = 'a'.repeat(40);
const SNAP_2 = 'b'.repeat(40);

/** A `.bitmap` in the exact shape bit writes it (schema 17) — what `git show` hands the parser. */
function bitmapContent({
  lane,
  components = { comp1: SNAP_1, comp2: SNAP_2 },
  prefix = '/**\n * DO NOT EDIT THIS FILE\n */\n\n',
}: {
  lane?: { scope: string; name: string };
  components?: Record<string, string>;
  prefix?: string;
} = {}): string {
  const body: Record<string, any> = {};
  Object.entries(components).forEach(([name, version]) => {
    body[name] = { name, scope: DEFAULT_SCOPE, version, mainFile: 'index.js', rootDir: name };
  });
  if (lane) body._bit_lane = { id: lane, exported: true };
  body['$schema-version'] = '17.0.0';
  return `${prefix}${JSON.stringify(body, null, 4)}`;
}

/** a `.bitmap` carrying whatever `_bit_lane` value the caller wants to see rejected */
function bitmapWithRawLaneKey(laneKey: any): string {
  return JSON.stringify({
    comp1: { name: 'comp1', scope: DEFAULT_SCOPE, version: SNAP_1, mainFile: 'index.js', rootDir: 'comp1' },
    _bit_lane: laneKey,
    '$schema-version': '17.0.0',
  });
}

const onLane = (name = 'my-lane', scope = DEFAULT_SCOPE) =>
  parseBranchBitmap(bitmapContent({ lane: { scope, name } }), DEFAULT_SCOPE) as NonNullable<
    ReturnType<typeof parseBranchBitmap>
  >;

describe('parseBranchBitmap', () => {
  it('reads the lane pointer scope-qualified — the attribution the ownership rule is built on', () => {
    expect(onLane('my-lane', 'other.scope').laneIdStr).to.equal('other.scope/my-lane');
  });

  it('reads every component at the exact version the branch records', () => {
    expect(onLane().versions).to.deep.equal({
      [`${DEFAULT_SCOPE}/comp1`]: SNAP_1,
      [`${DEFAULT_SCOPE}/comp2`]: SNAP_2,
    });
  });

  it('survives the comment header bit prefixes every `.bitmap` with', () => {
    // `.bitmap` is JSON-with-comments; a throw here silently degrades every branch to "not ours".
    const state = parseBranchBitmap(
      bitmapContent({ lane: { scope: DEFAULT_SCOPE, name: 'my-lane' }, prefix: '/* generated, do not edit */\n' }),
      DEFAULT_SCOPE
    );
    expect(state?.laneIdStr).to.equal(`${DEFAULT_SCOPE}/my-lane`);
  });

  /**
   * Only a pointer bit marked exported, carrying a scoped id, is attribution. Honouring anything else
   * would read "lane removed" for a lane that never existed remotely and retire a developer branch —
   * and a bare name could still trigger the branch-aliasing halt over a lane that does not exist.
   */
  const POINTERS: Array<[string, any, string | undefined]> = [
    ['bit marked it not exported', { id: { scope: DEFAULT_SCOPE, name: 'foo' }, exported: false }, undefined],
    ['`exported` is missing entirely', { id: { scope: DEFAULT_SCOPE, name: 'foo' } }, undefined],
    ['it is an empty object', {}, undefined],
    ['`id` is a string rather than a {scope, name}', { id: `${DEFAULT_SCOPE}/foo`, exported: true }, undefined],
    ['the lane id has no scope', { id: { scope: '', name: 'foo' }, exported: true }, undefined],
    // non-vacuity for the rows above: a well-formed pointer through the same helper DOES attribute
    [
      'bit has marked the lane exported',
      { id: { scope: DEFAULT_SCOPE, name: 'foo' }, exported: true },
      `${DEFAULT_SCOPE}/foo`,
    ],
  ];

  POINTERS.forEach(([name, laneKey, laneIdStr]) => {
    it(`withholds attribution unless the pointer is usable: ${name}`, () => {
      const state = parseBranchBitmap(bitmapWithRawLaneKey(laneKey), DEFAULT_SCOPE);
      expect(state?.laneIdStr).to.equal(laneIdStr);
    });
  });

  it('reports no lane pointer at all for a `.bitmap` on main — every ordinary developer branch', () => {
    const state = parseBranchBitmap(bitmapContent(), DEFAULT_SCOPE);
    expect(state).to.not.equal(undefined);
    expect(state?.laneIdStr).to.equal(undefined);
  });

  /** Every way of not knowing must resolve to the answer that licenses nothing (no branch retired). */
  const UNREADABLE: Array<[string, string | undefined]> = [
    ['a `.bitmap` that is not valid JSON', '{ this is not json'],
    ['a file git could not produce at all', undefined],
    ['an empty file', ''],
    ['a whitespace-only file', '   \n '],
    [
      'an entry bit itself refuses — a scoped component with no version',
      JSON.stringify({
        comp1: { name: 'comp1', scope: DEFAULT_SCOPE, mainFile: 'index.js', rootDir: 'comp1' },
        '$schema-version': '17.0.0',
      }),
    ],
    [
      'two components claiming the same rootDir',
      JSON.stringify({
        comp1: { name: 'comp1', scope: DEFAULT_SCOPE, version: SNAP_1, mainFile: 'index.js', rootDir: 'shared' },
        comp2: { name: 'comp2', scope: DEFAULT_SCOPE, version: SNAP_2, mainFile: 'index.js', rootDir: 'shared' },
        '$schema-version': '17.0.0',
      }),
    ],
  ];

  UNREADABLE.forEach(([name, content]) => {
    it(`degrades to undefined rather than guessing, for ${name}`, () => {
      expect(parseBranchBitmap(content, DEFAULT_SCOPE)).to.equal(undefined);
    });
  });

  it('falls back to the repository default scope for a component `.bitmap` does not scope', () => {
    // `latest` can never equal a snap hash, so such a pair reads as not-converged — the safe direction.
    const content = JSON.stringify({
      comp1: { name: 'comp1', scope: '', defaultScope: DEFAULT_SCOPE, mainFile: 'index.js', rootDir: 'comp1' },
      '$schema-version': '17.0.0',
    });
    expect(parseBranchBitmap(content, DEFAULT_SCOPE)?.versions).to.deep.equal({
      [`${DEFAULT_SCOPE}/comp1`]: 'latest',
    });
  });
});

describe('fingerprintIdVersions', () => {
  it('is a single 40-hex token, and stable under reordering', () => {
    // A single token survives being written into a commit trailer; order-stability keeps neither
    // listing order looking like a state change.
    const a = `${DEFAULT_SCOPE}/comp1@${SNAP_1}`;
    const b = `${DEFAULT_SCOPE}/comp2@${SNAP_2}`;
    expect(fingerprintIdVersions([a])).to.match(/^[0-9a-f]{40}$/);
    expect(fingerprintIdVersions([a, b])).to.equal(fingerprintIdVersions([b, a]));
  });
});

describe('branchStateFingerprint', () => {
  const laneIds = [`${DEFAULT_SCOPE}/comp1`, `${DEFAULT_SCOPE}/comp2`];

  it('equals the lane fingerprint when the branch records every lane component at the lane head', () => {
    // Computed the way `laneHeadFingerprint` computes it — the two sides must be comparable.
    const laneSide = fingerprintIdVersions([`${DEFAULT_SCOPE}/comp1@${SNAP_1}`, `${DEFAULT_SCOPE}/comp2@${SNAP_2}`]);
    expect(branchStateFingerprint(onLane(), laneIds)).to.equal(laneSide);
  });

  it('differs when the lane moved a component the branch has not caught up with', () => {
    const laneMoved = fingerprintIdVersions([
      `${DEFAULT_SCOPE}/comp1@${SNAP_1}`,
      `${DEFAULT_SCOPE}/comp2@${'c'.repeat(40)}`,
    ]);
    expect(branchStateFingerprint(onLane(), laneIds)).to.not.equal(laneMoved);
  });

  it('counts a lane component the branch does not have at all', () => {
    // Without the placeholder, "the lane grew a component" would fingerprint identically to "converged".
    const grown = [...laneIds, `${DEFAULT_SCOPE}/comp3`];
    expect(branchStateFingerprint(onLane(), grown)).to.not.equal(branchStateFingerprint(onLane(), laneIds));
    expect(branchStateFingerprint(onLane(), grown)).to.equal(
      fingerprintIdVersions([
        `${DEFAULT_SCOPE}/comp1@${SNAP_1}`,
        `${DEFAULT_SCOPE}/comp2@${SNAP_2}`,
        `${DEFAULT_SCOPE}/comp3@${ABSENT_ON_BRANCH}`,
      ])
    );
  });

  it('ignores components the branch has that are not on the lane', () => {
    // The `.bitmap` also carries non-lane components at their main versions; counting those would make
    // an untouched pair read as diverged after any unrelated release.
    const withExtra = parseBranchBitmap(
      bitmapContent({
        lane: { scope: DEFAULT_SCOPE, name: 'my-lane' },
        components: { comp1: SNAP_1, comp2: SNAP_2, comp9: '0.0.7' },
      }),
      DEFAULT_SCOPE
    ) as NonNullable<ReturnType<typeof parseBranchBitmap>>;
    expect(branchStateFingerprint(withExtra, laneIds)).to.equal(branchStateFingerprint(onLane(), laneIds));
  });
});
