// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Generated by scripts/generate-command-index.mjs
// (RFC: ESM Migration with Lazy-Loaded Aspects, Slice 2)
// To regenerate, run: npm run generate-command-index

export interface CommandIndexEntry {
  /** Command name (first word of `Command.name` — strips the `<arg>` / `[arg]` parts). */
  name: string;
  /** Full `Command.name` (including positional patterns like `<arg>` / `[arg...]`), only set when it differs from `name`. The lazy stub trampoline uses this so yargs accepts positional arguments. */
  pattern?: string;
  /** Aspect id that registered the command. */
  aspectId: string;
  alias?: string;
  description?: string;
  group?: string;
  private?: boolean;
  loader?: boolean;
  loadAspects?: boolean;
  remoteOp?: boolean;
  skipWorkspace?: boolean;
  /** Sub-command entries (same shape, inherits aspectId from parent). */
  subCommands?: CommandIndexEntry[];
}

export const COMMAND_INDEX: CommandIndexEntry[] = [
  {
    "name": "add",
    "aspectId": "teambit.component/tracker",
    "pattern": "add [path...]",
    "alias": "a",
    "description": "track existing directory contents as new components in the workspace",
    "group": "component-development"
  },
  {
    "name": "artifacts",
    "aspectId": "teambit.pipelines/builder",
    "pattern": "artifacts <component-pattern>",
    "description": "view and download build artifacts",
    "group": "testing"
  },
  {
    "name": "aspect",
    "aspectId": "teambit.harmony/aspect",
    "pattern": "aspect <sub-command>",
    "description": "manage component aspects and their configurations",
    "group": "component-config",
    "subCommands": [
      {
        "name": "get",
        "aspectId": "teambit.harmony/aspect",
        "pattern": "get <component-name>",
        "description": "list the aspects set on a component, as well as their configs and data",
        "group": "info-analysis"
      },
      {
        "name": "list",
        "aspectId": "teambit.harmony/aspect",
        "pattern": "list [pattern]",
        "description": "list all aspects configured on component(s)",
        "group": "info-analysis"
      },
      {
        "name": "list-core",
        "aspectId": "teambit.harmony/aspect",
        "description": "list all core aspects",
        "group": "info-analysis"
      },
      {
        "name": "set",
        "aspectId": "teambit.harmony/aspect",
        "pattern": "set <pattern> <aspect-id> [config]",
        "description": "set components with an aspect to extend their development tools, metadata and (possibly) artifacts",
        "group": "component-config"
      },
      {
        "name": "unset",
        "aspectId": "teambit.harmony/aspect",
        "pattern": "unset <pattern> <aspect-id>",
        "description": "unset an aspect from component(s).",
        "group": "component-config"
      },
      {
        "name": "update",
        "aspectId": "teambit.harmony/aspect",
        "pattern": "update <aspect-id> [pattern]",
        "description": "update a version of an aspect for all or specified components",
        "group": "component-config"
      }
    ]
  },
  {
    "name": "blame",
    "aspectId": "teambit.component/component-log",
    "pattern": "blame <filepath>",
    "description": "EXPERIMENTAL. show line-by-line authorship and modification history",
    "group": "version-control"
  },
  {
    "name": "build",
    "aspectId": "teambit.pipelines/builder",
    "pattern": "build [component-pattern]",
    "description": "run build pipeline tasks in isolated environments",
    "group": "component-development"
  },
  {
    "name": "capsule",
    "aspectId": "teambit.workspace/workspace",
    "description": "manage isolated component environments",
    "group": "advanced",
    "subCommands": [
      {
        "name": "create",
        "aspectId": "teambit.workspace/workspace",
        "pattern": "create [component-id...]",
        "description": "create capsules for components",
        "group": "advanced"
      },
      {
        "name": "delete",
        "aspectId": "teambit.workspace/workspace",
        "description": "delete capsules",
        "group": "advanced"
      },
      {
        "name": "list",
        "aspectId": "teambit.workspace/workspace",
        "description": "list the capsules generated for this workspace",
        "group": "advanced"
      }
    ]
  },
  {
    "name": "cat",
    "aspectId": "teambit.component/component",
    "pattern": "cat <component-id>",
    "description": "print source files or config of a component at a specific version",
    "group": "info-analysis",
    "skipWorkspace": true
  },
  {
    "name": "cat-component",
    "aspectId": "teambit.scope/scope",
    "pattern": "cat-component [id]",
    "alias": "cmp",
    "description": "cat a bit object by component-id",
    "group": "advanced",
    "private": true,
    "loadAspects": false
  },
  {
    "name": "cat-lane",
    "aspectId": "teambit.scope/scope",
    "pattern": "cat-lane <id>",
    "alias": "cl",
    "description": "cat a bit object by lane-name",
    "group": "advanced",
    "private": true,
    "loader": false,
    "loadAspects": false
  },
  {
    "name": "cat-lane-history",
    "aspectId": "teambit.lanes/lanes",
    "pattern": "cat-lane-history <lane-name>",
    "alias": "clh",
    "description": "cat lane-history object by lane-name",
    "group": "advanced",
    "private": true
  },
  {
    "name": "cat-object",
    "aspectId": "teambit.scope/scope",
    "pattern": "cat-object <hash>",
    "description": "cat a bit object by hash",
    "group": "advanced",
    "private": true,
    "loader": false,
    "loadAspects": false
  },
  {
    "name": "cat-scope",
    "aspectId": "teambit.scope/scope",
    "pattern": "cat-scope [scopePath]",
    "description": "cat a scope and show all the contents",
    "group": "advanced",
    "private": true,
    "loader": false,
    "loadAspects": false
  },
  {
    "name": "cat-version-history",
    "aspectId": "teambit.scope/version-history",
    "pattern": "cat-version-history <id>",
    "alias": "cvh",
    "description": "cat version-history object by component-id",
    "group": "advanced",
    "private": true,
    "loadAspects": false
  },
  {
    "name": "check-types",
    "aspectId": "teambit.typescript/typescript",
    "pattern": "check-types [component-pattern]",
    "description": "validate TypeScript type correctness",
    "group": "testing"
  },
  {
    "name": "checkout",
    "aspectId": "teambit.component/checkout",
    "pattern": "checkout <to> [component-pattern]",
    "alias": "U",
    "description": "switch between component versions or remove local changes",
    "group": "version-control"
  },
  {
    "name": "ci",
    "aspectId": "teambit.git/ci",
    "pattern": "ci <sub-command>",
    "description": "continuous integration commands for automated workflows",
    "group": "collaborate",
    "subCommands": [
      {
        "name": "merge",
        "aspectId": "teambit.git/ci",
        "description": "Tags and exports new semantic versions after merging a PR to main.",
        "group": "collaborate"
      },
      {
        "name": "pr",
        "aspectId": "teambit.git/ci",
        "description": "Exports a feature lane to Bit Cloud when a Pull Request is opened or updated.",
        "group": "collaborate"
      },
      {
        "name": "verify",
        "aspectId": "teambit.git/ci",
        "description": "Ensures the workspace passes CI checks on every commit.",
        "group": "development"
      }
    ]
  },
  {
    "name": "clear-cache",
    "aspectId": "teambit.bit/clear-cache",
    "alias": "cc",
    "description": "remove cached data to resolve stale data issues",
    "group": "system",
    "loader": false,
    "skipWorkspace": true
  },
  {
    "name": "compile",
    "aspectId": "teambit.compilation/compiler",
    "pattern": "compile [component-names...]",
    "description": "transpile component source files",
    "group": "component-development"
  },
  {
    "name": "completion",
    "aspectId": "teambit.harmony/cli",
    "description": "enable bash/zsh-completion shortcuts for commands and options",
    "group": "system",
    "private": true
  },
  {
    "name": "component-issues",
    "aspectId": "teambit.component/issues",
    "description": "list available component-issues",
    "group": "info-analysis",
    "private": true
  },
  {
    "name": "config",
    "aspectId": "teambit.harmony/config-store",
    "description": "manage Bit configuration settings",
    "group": "system",
    "loadAspects": false,
    "subCommands": [
      {
        "name": "del",
        "aspectId": "teambit.harmony/config-store",
        "pattern": "del <key>",
        "description": "delete given key from global configuration",
        "group": "ungrouped"
      },
      {
        "name": "get",
        "aspectId": "teambit.harmony/config-store",
        "pattern": "get <key>",
        "description": "get a value from global configuration",
        "group": "ungrouped"
      },
      {
        "name": "list",
        "aspectId": "teambit.harmony/config-store",
        "description": "list all configuration(s)",
        "group": "ungrouped"
      },
      {
        "name": "set",
        "aspectId": "teambit.harmony/config-store",
        "pattern": "set <key> <val>",
        "description": "set a configuration. default to save it globally",
        "group": "ungrouped",
        "skipWorkspace": true
      }
    ]
  },
  {
    "name": "create",
    "aspectId": "teambit.generator/generator",
    "pattern": "create <template-name> <component-names...>",
    "description": "scaffold new component(s) from a template (sources, config, and env)",
    "group": "component-development"
  },
  {
    "name": "delete",
    "aspectId": "teambit.component/remove",
    "pattern": "delete <component-pattern>",
    "description": "soft-delete components from remote scopes",
    "group": "collaborate",
    "remoteOp": true,
    "skipWorkspace": true
  },
  {
    "name": "dependents",
    "aspectId": "teambit.dependencies/dependencies",
    "pattern": "dependents <component-name>",
    "description": "show components that depend on the specified component",
    "group": "dependencies"
  },
  {
    "name": "deprecate",
    "aspectId": "teambit.component/deprecation",
    "pattern": "deprecate <component-name>",
    "alias": "d",
    "description": "mark a component as deprecated to discourage its use",
    "group": "collaborate",
    "remoteOp": true,
    "skipWorkspace": true
  },
  {
    "name": "details",
    "aspectId": "teambit.harmony/cli",
    "description": "show expanded details from the last command that provided them (e.g. tag, snap)",
    "group": "general",
    "loader": false,
    "loadAspects": false,
    "skipWorkspace": true
  },
  {
    "name": "diff",
    "aspectId": "teambit.component/component-compare",
    "pattern": "diff [component-pattern] [version] [to-version]",
    "description": "compare component changes between versions or against the current workspace",
    "group": "info-analysis"
  },
  {
    "name": "doctor",
    "aspectId": "teambit.harmony/doctor",
    "pattern": "doctor [diagnosis-name]",
    "description": "diagnose and troubleshoot workspace issues",
    "group": "system",
    "loadAspects": false
  },
  {
    "name": "eject",
    "aspectId": "teambit.workspace/eject",
    "pattern": "eject <component-pattern>",
    "alias": "E",
    "description": "remove component from workspace and install it as npm package",
    "group": "dependencies"
  },
  {
    "name": "eject-conf",
    "aspectId": "teambit.workspace/workspace",
    "pattern": "eject-conf <pattern>",
    "description": "create component.json configuration files for components",
    "group": "component-config"
  },
  {
    "name": "envs",
    "aspectId": "teambit.envs/envs",
    "alias": "env",
    "description": "show components and their assigned environments",
    "group": "component-config",
    "subCommands": [
      {
        "name": "get",
        "aspectId": "teambit.envs/envs",
        "pattern": "get <component-name>",
        "description": "show config information from a component's env",
        "group": "component-config"
      },
      {
        "name": "list",
        "aspectId": "teambit.envs/envs",
        "description": "list all envs currently used in the workspace",
        "group": "component-config"
      },
      {
        "name": "replace",
        "aspectId": "teambit.envs/envs",
        "pattern": "replace <current-env> <new-env>",
        "description": "replace an existing env with another env for all components using the old env",
        "group": "component-config"
      },
      {
        "name": "set",
        "aspectId": "teambit.envs/envs",
        "pattern": "set <component-pattern> <env>",
        "description": "Assigns one or more components a development environment (env)",
        "group": "component-config"
      },
      {
        "name": "unset",
        "aspectId": "teambit.envs/envs",
        "pattern": "unset <component-pattern>",
        "description": "un-sets an env from components that were previously set by \"bit env set\" or by a component template",
        "group": "component-config"
      },
      {
        "name": "update",
        "aspectId": "teambit.envs/envs",
        "pattern": "update [env-id] [pattern]",
        "description": "update a version of an env for all components using that env",
        "group": "component-config"
      }
    ]
  },
  {
    "name": "export",
    "aspectId": "teambit.scope/export",
    "pattern": "export [component-patterns...]",
    "alias": "e",
    "description": "upload components to remote scopes",
    "group": "collaborate",
    "remoteOp": true
  },
  {
    "name": "fetch",
    "aspectId": "teambit.scope/importer",
    "pattern": "fetch [ids...]",
    "description": "fetch remote objects and store locally",
    "group": "collaborate",
    "private": true
  },
  {
    "name": "fork",
    "aspectId": "teambit.component/forking",
    "pattern": "fork <pattern> [target-component-name]",
    "description": "create a new component by copying from an existing one",
    "group": "collaborate",
    "remoteOp": true,
    "skipWorkspace": true
  },
  {
    "name": "format",
    "aspectId": "teambit.defender/formatter",
    "pattern": "format [component-pattern]",
    "description": "auto-format component source code",
    "group": "testing"
  },
  {
    "name": "generate-preview",
    "aspectId": "teambit.preview/preview",
    "pattern": "generate-preview [component-pattern]",
    "description": "generate preview bundle for components",
    "group": "run-serve",
    "private": true
  },
  {
    "name": "git",
    "aspectId": "teambit.git/git",
    "pattern": "git <sub-command>",
    "description": "Git utilities for Bit repositories",
    "group": "workspace-tools",
    "subCommands": [
      {
        "name": "merge-bitmaps",
        "aspectId": "teambit.git/git",
        "pattern": "merge-bitmaps <ancestor> <current> <other>",
        "description": "a special command to merge conflicting bitmap files during git merge",
        "group": "workspace-tools",
        "private": true
      },
      {
        "name": "set-merge-driver",
        "aspectId": "teambit.git/git",
        "alias": "smd",
        "description": "setup bit's git merge driver for bitmap files",
        "group": "workspace-tools"
      }
    ]
  },
  {
    "name": "globals",
    "aspectId": "teambit.harmony/global-config",
    "description": "display global directories and paths used by Bit",
    "group": "system"
  },
  {
    "name": "graph",
    "aspectId": "teambit.component/graph",
    "pattern": "graph [id]",
    "description": "visualize component dependencies as a graph image",
    "group": "info-analysis",
    "remoteOp": true
  },
  {
    "name": "import",
    "aspectId": "teambit.scope/importer",
    "pattern": "import [component-patterns...]",
    "description": "bring components from remote scopes into your workspace",
    "group": "collaborate",
    "remoteOp": true
  },
  {
    "name": "init",
    "aspectId": "teambit.harmony/host-initializer",
    "pattern": "init [path]",
    "description": "initialize a Bit workspace in an existing project",
    "group": "workspace-setup",
    "loadAspects": false,
    "skipWorkspace": true
  },
  {
    "name": "insights",
    "aspectId": "teambit.explorer/insights",
    "pattern": "insights [names...]",
    "description": "Insights on component graph",
    "group": "workspace-tools",
    "private": true
  },
  {
    "name": "install",
    "aspectId": "teambit.workspace/install",
    "pattern": "install [packages...]",
    "alias": "in",
    "description": "install workspace dependencies",
    "group": "dependencies"
  },
  {
    "name": "link",
    "aspectId": "teambit.workspace/install",
    "pattern": "link [component-names...]",
    "description": "create links between components and node_modules",
    "group": "dependencies"
  },
  {
    "name": "lint",
    "aspectId": "teambit.defender/linter",
    "pattern": "lint [component-pattern]",
    "description": "analyze component code for issues and style violations",
    "group": "testing"
  },
  {
    "name": "list",
    "aspectId": "teambit.component/lister",
    "pattern": "list [remote-scope]",
    "alias": "ls",
    "description": "display components in workspace or remote scope",
    "group": "info-analysis",
    "loadAspects": false,
    "remoteOp": true,
    "skipWorkspace": true
  },
  {
    "name": "local-only",
    "aspectId": "teambit.workspace/workspace",
    "pattern": "local-only <sub-command>",
    "description": "manage components that exist only in the workspace",
    "group": "component-config",
    "subCommands": [
      {
        "name": "list",
        "aspectId": "teambit.workspace/workspace",
        "description": "list all local-only components",
        "group": "ungrouped"
      },
      {
        "name": "set",
        "aspectId": "teambit.workspace/workspace",
        "pattern": "set <component-pattern>",
        "description": "set a component as local-only",
        "group": "ungrouped"
      },
      {
        "name": "unset",
        "aspectId": "teambit.workspace/workspace",
        "pattern": "unset <component-pattern>",
        "description": "remove a component from local-only",
        "group": "ungrouped"
      }
    ]
  },
  {
    "name": "log",
    "aspectId": "teambit.component/component-log",
    "pattern": "log <id>",
    "description": "display component version history",
    "group": "version-control",
    "remoteOp": true,
    "skipWorkspace": true
  },
  {
    "name": "log-file",
    "aspectId": "teambit.component/component-log",
    "pattern": "log-file <filepath>",
    "description": "EXPERIMENTAL. display history of changes to a specific file",
    "group": "version-control"
  },
  {
    "name": "login",
    "aspectId": "teambit.cloud/cloud",
    "description": "authenticate with Bit Cloud for component publishing and collaboration",
    "group": "auth",
    "loadAspects": false,
    "remoteOp": true,
    "skipWorkspace": true
  },
  {
    "name": "logout",
    "aspectId": "teambit.cloud/cloud",
    "description": "sign out of Bit Cloud and clear authentication tokens",
    "group": "auth",
    "loadAspects": false,
    "skipWorkspace": true
  },
  {
    "name": "mcp-server",
    "aspectId": "teambit.mcp/cli-mcp-server",
    "pattern": "mcp-server [sub-command]",
    "description": "start Model Context Protocol server for AI assistants",
    "group": "advanced",
    "loader": false,
    "subCommands": [
      {
        "name": "rules",
        "aspectId": "teambit.mcp/cli-mcp-server",
        "pattern": "rules [editor]",
        "description": "Write Bit MCP rules/instructions file for VS Code, Cursor, Roo Code, Cline, Claude Code, or print to screen",
        "group": "ungrouped"
      },
      {
        "name": "setup",
        "aspectId": "teambit.mcp/cli-mcp-server",
        "pattern": "setup [editor]",
        "description": "Setup MCP integration with VS Code, Cursor, Windsurf, Roo Code, Cline, Claude Code, or other editors",
        "group": "ungrouped"
      },
      {
        "name": "start",
        "aspectId": "teambit.mcp/cli-mcp-server",
        "description": "Start the MCP server",
        "group": "advanced",
        "loader": false
      }
    ]
  },
  {
    "name": "merge",
    "aspectId": "teambit.component/merging",
    "pattern": "merge [component-pattern]",
    "description": "merge diverged component history when local and remote have different versions",
    "group": "version-control"
  },
  {
    "name": "mini-status",
    "aspectId": "teambit.component/status",
    "pattern": "mini-status [component-pattern]",
    "alias": "ms",
    "description": "basic status for fast execution",
    "group": "info-analysis",
    "private": true,
    "loadAspects": false
  },
  {
    "name": "move",
    "aspectId": "teambit.component/mover",
    "pattern": "move <current-component-dir> <new-component-dir>",
    "alias": "mv",
    "description": "relocate a component to a different directory",
    "group": "component-development"
  },
  {
    "name": "new",
    "aspectId": "teambit.generator/generator",
    "pattern": "new <template-name> <workspace-name>",
    "description": "create a new Bit workspace from a template",
    "group": "workspace-setup"
  },
  {
    "name": "npmrc",
    "aspectId": "teambit.cloud/cloud",
    "pattern": "npmrc [sub-command]",
    "description": "configure .npmrc file with Bit Cloud registry and authentication settings",
    "group": "auth",
    "skipWorkspace": true,
    "subCommands": [
      {
        "name": "generate",
        "aspectId": "teambit.cloud/cloud",
        "description": "update npmrc file with scope, registry, and token information from bit.cloud",
        "group": "auth"
      }
    ]
  },
  {
    "name": "pack",
    "aspectId": "teambit.pkg/pkg",
    "pattern": "pack <componentId> [scopePath]",
    "description": "create tar for npm publish",
    "group": "collaborate",
    "private": true
  },
  {
    "name": "pattern",
    "aspectId": "teambit.workspace/workspace",
    "pattern": "pattern <pattern>",
    "description": "test and validate component patterns",
    "group": "info-analysis",
    "remoteOp": true
  },
  {
    "name": "publish",
    "aspectId": "teambit.pkg/pkg",
    "pattern": "publish <component-pattern>",
    "description": "publish components to npm (npm publish)",
    "group": "collaborate",
    "private": true
  },
  {
    "name": "recover",
    "aspectId": "teambit.component/remove",
    "pattern": "recover <component-pattern>",
    "description": "restore soft-deleted components",
    "group": "collaborate"
  },
  {
    "name": "refactor",
    "aspectId": "teambit.component/refactoring",
    "pattern": "refactor <sub-command>",
    "description": "automatically refactor component source code",
    "group": "workspace-tools",
    "subCommands": [
      {
        "name": "dependency-name",
        "aspectId": "teambit.component/refactoring",
        "pattern": "dependency-name <old-id> <new-id>",
        "description": "replace the dependency's old package-name with a new one in the code",
        "group": "workspace-tools"
      }
    ]
  },
  {
    "name": "remote",
    "aspectId": "teambit.harmony/global-config",
    "description": "manage remote scopes for self-hosted environments",
    "group": "collaborate",
    "loadAspects": false,
    "subCommands": [
      {
        "name": "add",
        "aspectId": "teambit.harmony/global-config",
        "pattern": "add <url>",
        "description": "add a bare-scope as a remote",
        "group": "ungrouped",
        "loadAspects": false
      },
      {
        "name": "del",
        "aspectId": "teambit.harmony/global-config",
        "pattern": "del <name>",
        "description": "remove a tracked bit remote",
        "group": "ungrouped",
        "loadAspects": false
      },
      {
        "name": "list",
        "aspectId": "teambit.harmony/global-config",
        "description": "list all configured remotes",
        "group": "collaborate",
        "loadAspects": false
      }
    ]
  },
  {
    "name": "remove",
    "aspectId": "teambit.component/remove",
    "pattern": "remove <component-pattern>",
    "alias": "rm",
    "description": "untrack components from the workspace",
    "group": "component-development",
    "remoteOp": true,
    "skipWorkspace": true
  },
  {
    "name": "rename",
    "aspectId": "teambit.component/renaming",
    "pattern": "rename <current-name> <new-name>",
    "description": "change a component name",
    "group": "component-development",
    "remoteOp": true,
    "skipWorkspace": true
  },
  {
    "name": "reset",
    "aspectId": "teambit.component/snapping",
    "pattern": "reset [component-pattern]",
    "description": "revert local tags and snaps to previous versions",
    "group": "version-control"
  },
  {
    "name": "resume-export",
    "aspectId": "teambit.scope/export",
    "pattern": "resume-export <export-id> <remotes...>",
    "description": "EXPERIMENTAL. resume failed export",
    "group": "advanced",
    "private": true,
    "remoteOp": true
  },
  {
    "name": "revert",
    "aspectId": "teambit.component/checkout",
    "pattern": "revert <component-pattern> <to>",
    "description": "replace component files with specified version while preserving current version",
    "group": "version-control"
  },
  {
    "name": "ripple",
    "aspectId": "teambit.cloud/ripple",
    "pattern": "ripple <sub-command>",
    "description": "manage Ripple CI jobs on bit.cloud",
    "group": "collaborate",
    "remoteOp": true,
    "skipWorkspace": true,
    "subCommands": [
      {
        "name": "errors",
        "aspectId": "teambit.cloud/ripple",
        "pattern": "errors [job-id]",
        "description": "show build errors for a Ripple CI job (auto-detects current lane, or your last export when on main)",
        "group": "ungrouped",
        "remoteOp": true,
        "skipWorkspace": true
      },
      {
        "name": "list",
        "aspectId": "teambit.cloud/ripple",
        "description": "list recent Ripple CI jobs (filtered by workspace owner by default)",
        "group": "ungrouped",
        "remoteOp": true,
        "skipWorkspace": true
      },
      {
        "name": "log",
        "aspectId": "teambit.cloud/ripple",
        "pattern": "log [job-id]",
        "description": "show job details and component build task summaries (auto-detects current lane, or your last export when on main)",
        "group": "ungrouped",
        "remoteOp": true,
        "skipWorkspace": true
      },
      {
        "name": "retry",
        "aspectId": "teambit.cloud/ripple",
        "pattern": "retry [job-id]",
        "description": "retry a failed Ripple CI job (auto-detects current lane when no job-id given)",
        "group": "ungrouped",
        "remoteOp": true,
        "skipWorkspace": true
      },
      {
        "name": "stop",
        "aspectId": "teambit.cloud/ripple",
        "pattern": "stop [job-id]",
        "description": "stop a running Ripple CI job (auto-detects current lane when no job-id given)",
        "group": "ungrouped",
        "remoteOp": true,
        "skipWorkspace": true
      }
    ]
  },
  {
    "name": "run",
    "aspectId": "teambit.harmony/application",
    "pattern": "run [app-name]",
    "alias": "c",
    "description": "start an application component locally",
    "group": "run-serve"
  },
  {
    "name": "run-action",
    "aspectId": "teambit.scope/scope",
    "pattern": "run-action <action-name> <remote> <options>",
    "description": "run an action on a remote",
    "group": "advanced",
    "private": true,
    "loadAspects": false
  },
  {
    "name": "schema",
    "aspectId": "teambit.semantics/schema",
    "pattern": "schema <pattern>",
    "alias": "api",
    "description": "display component API schema and type definitions",
    "group": "info-analysis",
    "subCommands": [
      {
        "name": "diff",
        "aspectId": "teambit.semantics/schema",
        "pattern": "diff <component> <base-version> <compare-version>",
        "description": "show API changes between two versions of a component",
        "group": "info-analysis"
      }
    ]
  },
  {
    "name": "scope",
    "aspectId": "teambit.scope/scope",
    "pattern": "scope <sub-command>",
    "description": "manage component scope names and assignments",
    "group": "component-config",
    "subCommands": [
      {
        "name": "fork",
        "aspectId": "teambit.scope/scope",
        "pattern": "fork <original-scope> [new-scope] [pattern]",
        "description": "fork all components of the original-scope and refactor the source-code to use the new scope name",
        "group": "component-config"
      },
      {
        "name": "rename",
        "aspectId": "teambit.scope/scope",
        "pattern": "rename <current-scope-name> <new-scope-name>",
        "description": "rename the scope name for all components with the specified 'current scope name'. if exported, create new components and delete the original ones",
        "group": "component-config"
      },
      {
        "name": "rename-owner",
        "aspectId": "teambit.scope/scope",
        "pattern": "rename-owner <current-owner-name> <new-owner-name>",
        "description": "Renames the owner part of the scope-name for all components with the specified 'current owner name'",
        "group": "component-config"
      },
      {
        "name": "set",
        "aspectId": "teambit.scope/scope",
        "pattern": "set <scope-name> [component-pattern]",
        "description": "Sets the scope for specified component/s. If no component is specified, sets the default scope of the workspace",
        "group": "component-config"
      },
      {
        "name": "trust",
        "aspectId": "teambit.scope/scope",
        "pattern": "trust [action] [pattern]",
        "description": "manage which scopes are trusted to load aspects (envs, etc.) into the workspace's process",
        "group": "component-config",
        "loadAspects": false
      }
    ]
  },
  {
    "name": "script",
    "aspectId": "teambit.workspace/scripts",
    "pattern": "script [script-name]",
    "description": "run a script defined by the environment",
    "group": "development"
  },
  {
    "name": "search",
    "aspectId": "teambit.component/lister",
    "pattern": "search <query...>",
    "description": "search for components by keyword in the local workspace and remote bit cloud",
    "group": "info-analysis",
    "remoteOp": true,
    "skipWorkspace": true
  },
  {
    "name": "serve-preview",
    "aspectId": "teambit.preview/preview",
    "description": "serve local preview bundle for components",
    "group": "run-serve",
    "private": true
  },
  {
    "name": "server",
    "aspectId": "teambit.harmony/api-server",
    "description": "communicate with bit cli program via http requests",
    "group": "workspace-setup",
    "private": true
  },
  {
    "name": "set-peer",
    "aspectId": "teambit.dependencies/dependencies",
    "pattern": "set-peer <component-id> <range>",
    "description": "configure component to always be installed as peer dependency",
    "group": "dependencies"
  },
  {
    "name": "show",
    "aspectId": "teambit.component/component",
    "pattern": "show <component-name>",
    "description": "display component metadata, dependencies, and configuration",
    "group": "info-analysis"
  },
  {
    "name": "snap",
    "aspectId": "teambit.component/snapping",
    "pattern": "snap [component-pattern]",
    "description": "create immutable component snapshots for development versions",
    "group": "version-control"
  },
  {
    "name": "snap-distance",
    "aspectId": "teambit.component/snapping",
    "pattern": "snap-distance <component-id> [source-snap] [target-snap]",
    "description": "show common-snap and distance between two given snaps or between local and remote snaps",
    "group": "advanced",
    "private": true
  },
  {
    "name": "start",
    "aspectId": "teambit.ui-foundation/ui",
    "pattern": "start [component-pattern]",
    "alias": "c",
    "description": "launch the Bit development server",
    "group": "run-serve"
  },
  {
    "name": "stash",
    "aspectId": "teambit.component/stash",
    "pattern": "stash <sub-command>",
    "description": "temporarily save and restore component changes",
    "group": "version-control",
    "subCommands": [
      {
        "name": "list",
        "aspectId": "teambit.component/stash",
        "description": "list stash",
        "group": "version-control"
      },
      {
        "name": "load",
        "aspectId": "teambit.component/stash",
        "pattern": "load [stash-id]",
        "alias": "pop",
        "description": "apply the changes according to the stash. if no stash-id provided, it loads the latest stash",
        "group": "version-control"
      },
      {
        "name": "save",
        "aspectId": "teambit.component/stash",
        "alias": "s",
        "description": "stash modified components",
        "group": "version-control"
      }
    ]
  },
  {
    "name": "status",
    "aspectId": "teambit.component/status",
    "alias": "s",
    "description": "show workspace component status and issues",
    "group": "info-analysis"
  },
  {
    "name": "tag",
    "aspectId": "teambit.component/snapping",
    "pattern": "tag [component-patterns...]",
    "alias": "t",
    "description": "create immutable component snapshots with semantic version tags",
    "group": "version-control",
    "remoteOp": true
  },
  {
    "name": "templates",
    "aspectId": "teambit.generator/generator",
    "description": "list available templates for creating components and workspaces",
    "group": "component-development"
  },
  {
    "name": "test",
    "aspectId": "teambit.defender/tester",
    "pattern": "test [component-pattern]",
    "alias": "at",
    "description": "run component tests",
    "group": "testing"
  },
  {
    "name": "ui-build",
    "aspectId": "teambit.ui-foundation/ui",
    "pattern": "ui-build [type]",
    "alias": "c",
    "description": "build production assets for deployment.",
    "group": "run-serve",
    "private": true
  },
  {
    "name": "undeprecate",
    "aspectId": "teambit.component/deprecation",
    "pattern": "undeprecate <id>",
    "description": "remove the deprecation status from a component",
    "group": "collaborate",
    "remoteOp": true,
    "skipWorkspace": true
  },
  {
    "name": "uninstall",
    "aspectId": "teambit.workspace/install",
    "pattern": "uninstall [packages...]",
    "alias": "un",
    "description": "remove dependencies from workspace",
    "group": "dependencies"
  },
  {
    "name": "unset-peer",
    "aspectId": "teambit.dependencies/dependencies",
    "pattern": "unset-peer <component-id>",
    "description": "remove always-peer configuration from component",
    "group": "dependencies"
  },
  {
    "name": "unuse",
    "aspectId": "teambit.workspace/workspace",
    "pattern": "unuse <component-id>",
    "description": "unset aspects in the workspace config (opposite of \"use\" command)",
    "group": "workspace-setup",
    "private": true,
    "remoteOp": true
  },
  {
    "name": "update",
    "aspectId": "teambit.workspace/install",
    "pattern": "update [package-patterns...]",
    "alias": "up",
    "description": "update workspace dependencies to newer versions",
    "group": "dependencies"
  },
  {
    "name": "use",
    "aspectId": "teambit.workspace/workspace",
    "pattern": "use <component-id>",
    "description": "set aspects in the workspace/scope config to make them loadable by the workspace/scope",
    "group": "workspace-setup",
    "private": true,
    "remoteOp": true
  },
  {
    "name": "validate",
    "aspectId": "teambit.defender/validator",
    "pattern": "validate [component-pattern]",
    "description": "run type-checking, linting, and testing in sequence",
    "group": "testing"
  },
  {
    "name": "version",
    "aspectId": "teambit.harmony/cli",
    "description": "display the installed Bit version",
    "group": "system",
    "loader": false
  },
  {
    "name": "watch",
    "aspectId": "teambit.workspace/watcher",
    "description": "watch and compile components on file changes",
    "group": "component-development"
  },
  {
    "name": "whoami",
    "aspectId": "teambit.cloud/cloud",
    "description": "display the currently authenticated Bit Cloud user",
    "group": "auth",
    "skipWorkspace": true
  },
  {
    "name": "why",
    "aspectId": "teambit.dependencies/dependencies",
    "pattern": "why <dependency-name>",
    "description": "find components that use the specified dependency",
    "group": "dependencies"
  },
  {
    "name": "ws-config",
    "aspectId": "teambit.workspace/workspace-config-files",
    "pattern": "ws-config <sub-command>",
    "alias": "workspace-config",
    "description": "generate IDE configuration files",
    "group": "workspace-tools",
    "subCommands": [
      {
        "name": "clean",
        "aspectId": "teambit.workspace/workspace-config-files",
        "description": "clean (delete) written config files in the workspace. useful for IDEs",
        "group": "workspace-tools"
      },
      {
        "name": "list",
        "aspectId": "teambit.workspace/workspace-config-files",
        "description": "list config writers",
        "group": "workspace-tools"
      },
      {
        "name": "write",
        "aspectId": "teambit.workspace/workspace-config-files",
        "description": "write config files in the workspace. useful for IDEs",
        "group": "workspace-tools"
      }
    ]
  }
];
