// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Generated by scripts/generate-command-index.mjs
// (RFC: ESM Migration with Lazy-Loaded Aspects, Slice 2)
// To regenerate, run: npm run generate-command-index

export interface CommandIndexEntry {
  /** Command name (first word of `Command.name` — strips the `<arg>` / `[arg]` parts). */
  name: string;
  /** Aspect id that registered the command. */
  aspectId: string;
  alias?: string;
  description?: string;
  group?: string;
  private?: boolean;
  loader?: boolean;
  loadAspects?: boolean;
  remoteOp?: boolean;
  skipWorkspace?: boolean;
  /** Sub-command entries (same shape, inherits aspectId from parent). */
  subCommands?: CommandIndexEntry[];
}

export const COMMAND_INDEX: CommandIndexEntry[] = [
  {
    "name": "add",
    "aspectId": "teambit.component/tracker",
    "alias": "a",
    "description": "track existing directory contents as new components in the workspace",
    "group": "component-development"
  },
  {
    "name": "artifacts",
    "aspectId": "teambit.pipelines/builder",
    "description": "view and download build artifacts",
    "group": "testing"
  },
  {
    "name": "aspect",
    "aspectId": "teambit.harmony/aspect",
    "description": "manage component aspects and their configurations",
    "group": "component-config",
    "subCommands": [
      {
        "name": "get",
        "aspectId": "teambit.harmony/aspect",
        "description": "list the aspects set on a component, as well as their configs and data",
        "group": "info-analysis"
      },
      {
        "name": "list",
        "aspectId": "teambit.harmony/aspect",
        "description": "list all aspects configured on component(s)",
        "group": "info-analysis"
      },
      {
        "name": "list-core",
        "aspectId": "teambit.harmony/aspect",
        "description": "list all core aspects",
        "group": "info-analysis"
      },
      {
        "name": "set",
        "aspectId": "teambit.harmony/aspect",
        "description": "set components with an aspect to extend their development tools, metadata and (possibly) artifacts",
        "group": "component-config"
      },
      {
        "name": "unset",
        "aspectId": "teambit.harmony/aspect",
        "description": "unset an aspect from component(s).",
        "group": "component-config"
      },
      {
        "name": "update",
        "aspectId": "teambit.harmony/aspect",
        "description": "update a version of an aspect for all or specified components",
        "group": "component-config"
      }
    ]
  },
  {
    "name": "blame",
    "aspectId": "teambit.component/component-log",
    "description": "EXPERIMENTAL. show line-by-line authorship and modification history",
    "group": "version-control"
  },
  {
    "name": "build",
    "aspectId": "teambit.pipelines/builder",
    "description": "run build pipeline tasks in isolated environments",
    "group": "component-development"
  },
  {
    "name": "capsule",
    "aspectId": "teambit.workspace/workspace",
    "description": "manage isolated component environments",
    "group": "advanced",
    "subCommands": [
      {
        "name": "create",
        "aspectId": "teambit.workspace/workspace",
        "description": "create capsules for components",
        "group": "advanced"
      },
      {
        "name": "delete",
        "aspectId": "teambit.workspace/workspace",
        "description": "delete capsules",
        "group": "advanced"
      },
      {
        "name": "list",
        "aspectId": "teambit.workspace/workspace",
        "description": "list the capsules generated for this workspace",
        "group": "advanced"
      }
    ]
  },
  {
    "name": "cat",
    "aspectId": "teambit.component/component",
    "description": "print source files or config of a component at a specific version",
    "group": "info-analysis",
    "skipWorkspace": true
  },
  {
    "name": "cat-component",
    "aspectId": "teambit.scope/scope",
    "alias": "cmp",
    "description": "cat a bit object by component-id",
    "group": "advanced",
    "private": true,
    "loadAspects": false
  },
  {
    "name": "cat-lane",
    "aspectId": "teambit.scope/scope",
    "alias": "cl",
    "description": "cat a bit object by lane-name",
    "group": "advanced",
    "private": true,
    "loader": false,
    "loadAspects": false
  },
  {
    "name": "cat-lane-history",
    "aspectId": "teambit.lanes/lanes",
    "alias": "clh",
    "description": "cat lane-history object by lane-name",
    "group": "advanced",
    "private": true
  },
  {
    "name": "cat-object",
    "aspectId": "teambit.scope/scope",
    "description": "cat a bit object by hash",
    "group": "advanced",
    "private": true,
    "loader": false,
    "loadAspects": false
  },
  {
    "name": "cat-scope",
    "aspectId": "teambit.scope/scope",
    "description": "cat a scope and show all the contents",
    "group": "advanced",
    "private": true,
    "loader": false,
    "loadAspects": false
  },
  {
    "name": "cat-version-history",
    "aspectId": "teambit.scope/version-history",
    "alias": "cvh",
    "description": "cat version-history object by component-id",
    "group": "advanced",
    "private": true,
    "loadAspects": false
  },
  {
    "name": "check-types",
    "aspectId": "teambit.typescript/typescript",
    "description": "validate TypeScript type correctness",
    "group": "testing"
  },
  {
    "name": "ci",
    "aspectId": "teambit.git/ci",
    "description": "continuous integration commands for automated workflows",
    "group": "collaborate",
    "subCommands": [
      {
        "name": "merge",
        "aspectId": "teambit.git/ci",
        "description": "Tags and exports new semantic versions after merging a PR to main.",
        "group": "collaborate"
      },
      {
        "name": "pr",
        "aspectId": "teambit.git/ci",
        "description": "Exports a feature lane to Bit Cloud when a Pull Request is opened or updated.",
        "group": "collaborate"
      },
      {
        "name": "verify",
        "aspectId": "teambit.git/ci",
        "description": "Ensures the workspace passes CI checks on every commit.",
        "group": "development"
      }
    ]
  },
  {
    "name": "clear-cache",
    "aspectId": "teambit.bit/clear-cache",
    "alias": "cc",
    "description": "remove cached data to resolve stale data issues",
    "group": "system",
    "loader": false,
    "skipWorkspace": true
  },
  {
    "name": "compile",
    "aspectId": "teambit.compilation/compiler",
    "description": "transpile component source files",
    "group": "component-development"
  },
  {
    "name": "component-issues",
    "aspectId": "teambit.component/issues",
    "description": "list available component-issues",
    "group": "info-analysis",
    "private": true
  },
  {
    "name": "config",
    "aspectId": "teambit.harmony/config-store",
    "description": "manage Bit configuration settings",
    "group": "system",
    "loadAspects": false,
    "subCommands": [
      {
        "name": "del",
        "aspectId": "teambit.harmony/config-store",
        "description": "delete given key from global configuration",
        "group": "ungrouped"
      },
      {
        "name": "get",
        "aspectId": "teambit.harmony/config-store",
        "description": "get a value from global configuration",
        "group": "ungrouped"
      },
      {
        "name": "list",
        "aspectId": "teambit.harmony/config-store",
        "description": "list all configuration(s)",
        "group": "ungrouped"
      },
      {
        "name": "set",
        "aspectId": "teambit.harmony/config-store",
        "description": "set a configuration. default to save it globally",
        "group": "ungrouped",
        "skipWorkspace": true
      }
    ]
  },
  {
    "name": "create",
    "aspectId": "teambit.generator/generator",
    "description": "scaffold new component(s) from a template (sources, config, and env)",
    "group": "component-development"
  },
  {
    "name": "dependents",
    "aspectId": "teambit.dependencies/dependencies",
    "description": "show components that depend on the specified component",
    "group": "dependencies"
  },
  {
    "name": "details",
    "aspectId": "teambit.harmony/cli",
    "description": "show expanded details from the last command that provided them (e.g. tag, snap)",
    "group": "general",
    "loader": false,
    "loadAspects": false,
    "skipWorkspace": true
  },
  {
    "name": "diff",
    "aspectId": "teambit.component/component-compare",
    "description": "compare component changes between versions or against the current workspace",
    "group": "info-analysis"
  },
  {
    "name": "doctor",
    "aspectId": "teambit.harmony/doctor",
    "description": "diagnose and troubleshoot workspace issues",
    "group": "system",
    "loadAspects": false
  },
  {
    "name": "eject",
    "aspectId": "teambit.workspace/eject",
    "alias": "E",
    "description": "remove component from workspace and install it as npm package",
    "group": "dependencies"
  },
  {
    "name": "eject-conf",
    "aspectId": "teambit.workspace/workspace",
    "description": "create component.json configuration files for components",
    "group": "component-config"
  },
  {
    "name": "envs",
    "aspectId": "teambit.envs/envs",
    "alias": "env",
    "description": "show components and their assigned environments",
    "group": "component-config",
    "subCommands": [
      {
        "name": "get",
        "aspectId": "teambit.envs/envs",
        "description": "show config information from a component's env",
        "group": "component-config"
      },
      {
        "name": "list",
        "aspectId": "teambit.envs/envs",
        "description": "list all envs currently used in the workspace",
        "group": "component-config"
      },
      {
        "name": "replace",
        "aspectId": "teambit.envs/envs",
        "description": "replace an existing env with another env for all components using the old env",
        "group": "component-config"
      },
      {
        "name": "set",
        "aspectId": "teambit.envs/envs",
        "description": "Assigns one or more components a development environment (env)",
        "group": "component-config"
      },
      {
        "name": "unset",
        "aspectId": "teambit.envs/envs",
        "description": "un-sets an env from components that were previously set by \"bit env set\" or by a component template",
        "group": "component-config"
      },
      {
        "name": "update",
        "aspectId": "teambit.envs/envs",
        "description": "update a version of an env for all components using that env",
        "group": "component-config"
      }
    ]
  },
  {
    "name": "export",
    "aspectId": "teambit.scope/export",
    "alias": "e",
    "description": "upload components to remote scopes",
    "group": "collaborate",
    "remoteOp": true
  },
  {
    "name": "fetch",
    "aspectId": "teambit.scope/importer",
    "description": "fetch remote objects and store locally",
    "group": "collaborate",
    "private": true
  },
  {
    "name": "fork",
    "aspectId": "teambit.component/forking",
    "description": "create a new component by copying from an existing one",
    "group": "collaborate",
    "remoteOp": true,
    "skipWorkspace": true
  },
  {
    "name": "format",
    "aspectId": "teambit.defender/formatter",
    "description": "auto-format component source code",
    "group": "testing"
  },
  {
    "name": "generate-preview",
    "aspectId": "teambit.preview/preview",
    "description": "generate preview bundle for components",
    "group": "run-serve",
    "private": true
  },
  {
    "name": "git",
    "aspectId": "teambit.git/git",
    "description": "Git utilities for Bit repositories",
    "group": "workspace-tools",
    "subCommands": [
      {
        "name": "merge-bitmaps",
        "aspectId": "teambit.git/git",
        "description": "a special command to merge conflicting bitmap files during git merge",
        "group": "workspace-tools",
        "private": true
      },
      {
        "name": "set-merge-driver",
        "aspectId": "teambit.git/git",
        "alias": "smd",
        "description": "setup bit's git merge driver for bitmap files",
        "group": "workspace-tools"
      }
    ]
  },
  {
    "name": "graph",
    "aspectId": "teambit.component/graph",
    "description": "visualize component dependencies as a graph image",
    "group": "info-analysis",
    "remoteOp": true
  },
  {
    "name": "init",
    "aspectId": "teambit.harmony/host-initializer",
    "description": "initialize a Bit workspace in an existing project",
    "group": "workspace-setup",
    "loadAspects": false,
    "skipWorkspace": true
  },
  {
    "name": "insights",
    "aspectId": "teambit.explorer/insights",
    "description": "Insights on component graph",
    "group": "workspace-tools",
    "private": true
  },
  {
    "name": "install",
    "aspectId": "teambit.workspace/install",
    "alias": "in",
    "description": "install workspace dependencies",
    "group": "dependencies"
  },
  {
    "name": "link",
    "aspectId": "teambit.workspace/install",
    "description": "create links between components and node_modules",
    "group": "dependencies"
  },
  {
    "name": "lint",
    "aspectId": "teambit.defender/linter",
    "description": "analyze component code for issues and style violations",
    "group": "testing"
  },
  {
    "name": "local-only",
    "aspectId": "teambit.workspace/workspace",
    "description": "manage components that exist only in the workspace",
    "group": "component-config",
    "subCommands": [
      {
        "name": "list",
        "aspectId": "teambit.workspace/workspace",
        "description": "list all local-only components",
        "group": "ungrouped"
      },
      {
        "name": "set",
        "aspectId": "teambit.workspace/workspace",
        "description": "set a component as local-only",
        "group": "ungrouped"
      },
      {
        "name": "unset",
        "aspectId": "teambit.workspace/workspace",
        "description": "remove a component from local-only",
        "group": "ungrouped"
      }
    ]
  },
  {
    "name": "login",
    "aspectId": "teambit.cloud/cloud",
    "description": "authenticate with Bit Cloud for component publishing and collaboration",
    "group": "auth",
    "loadAspects": false,
    "remoteOp": true,
    "skipWorkspace": true
  },
  {
    "name": "logout",
    "aspectId": "teambit.cloud/cloud",
    "description": "sign out of Bit Cloud and clear authentication tokens",
    "group": "auth",
    "loadAspects": false,
    "skipWorkspace": true
  },
  {
    "name": "mcp-server",
    "aspectId": "teambit.mcp/cli-mcp-server",
    "description": "start Model Context Protocol server for AI assistants",
    "group": "advanced",
    "loader": false,
    "subCommands": [
      {
        "name": "rules",
        "aspectId": "teambit.mcp/cli-mcp-server",
        "description": "Write Bit MCP rules/instructions file for VS Code, Cursor, Roo Code, Cline, Claude Code, or print to screen",
        "group": "ungrouped"
      },
      {
        "name": "setup",
        "aspectId": "teambit.mcp/cli-mcp-server",
        "description": "Setup MCP integration with VS Code, Cursor, Windsurf, Roo Code, Cline, Claude Code, or other editors",
        "group": "ungrouped"
      },
      {
        "name": "start",
        "aspectId": "teambit.mcp/cli-mcp-server",
        "description": "Start the MCP server",
        "group": "advanced",
        "loader": false
      }
    ]
  },
  {
    "name": "merge",
    "aspectId": "teambit.component/merging",
    "description": "merge diverged component history when local and remote have different versions",
    "group": "version-control"
  },
  {
    "name": "mini-status",
    "aspectId": "teambit.component/status",
    "alias": "ms",
    "description": "basic status for fast execution",
    "group": "info-analysis",
    "private": true,
    "loadAspects": false
  },
  {
    "name": "move",
    "aspectId": "teambit.component/mover",
    "alias": "mv",
    "description": "relocate a component to a different directory",
    "group": "component-development"
  },
  {
    "name": "new",
    "aspectId": "teambit.generator/generator",
    "description": "create a new Bit workspace from a template",
    "group": "workspace-setup"
  },
  {
    "name": "npmrc",
    "aspectId": "teambit.cloud/cloud",
    "description": "configure .npmrc file with Bit Cloud registry and authentication settings",
    "group": "auth",
    "skipWorkspace": true,
    "subCommands": [
      {
        "name": "generate",
        "aspectId": "teambit.cloud/cloud",
        "description": "update npmrc file with scope, registry, and token information from bit.cloud",
        "group": "auth"
      }
    ]
  },
  {
    "name": "pack",
    "aspectId": "teambit.pkg/pkg",
    "description": "create tar for npm publish",
    "group": "collaborate",
    "private": true
  },
  {
    "name": "pattern",
    "aspectId": "teambit.workspace/workspace",
    "description": "test and validate component patterns",
    "group": "info-analysis",
    "remoteOp": true
  },
  {
    "name": "publish",
    "aspectId": "teambit.pkg/pkg",
    "description": "publish components to npm (npm publish)",
    "group": "collaborate",
    "private": true
  },
  {
    "name": "recover",
    "aspectId": "teambit.component/remove",
    "description": "restore soft-deleted components",
    "group": "collaborate"
  },
  {
    "name": "refactor",
    "aspectId": "teambit.component/refactoring",
    "description": "automatically refactor component source code",
    "group": "workspace-tools",
    "subCommands": [
      {
        "name": "dependency-name",
        "aspectId": "teambit.component/refactoring",
        "description": "replace the dependency's old package-name with a new one in the code",
        "group": "workspace-tools"
      }
    ]
  },
  {
    "name": "remote",
    "aspectId": "teambit.harmony/global-config",
    "description": "manage remote scopes for self-hosted environments",
    "group": "collaborate",
    "loadAspects": false,
    "subCommands": [
      {
        "name": "add",
        "aspectId": "teambit.harmony/global-config",
        "description": "add a bare-scope as a remote",
        "group": "ungrouped",
        "loadAspects": false
      },
      {
        "name": "del",
        "aspectId": "teambit.harmony/global-config",
        "description": "remove a tracked bit remote",
        "group": "ungrouped",
        "loadAspects": false
      },
      {
        "name": "list",
        "aspectId": "teambit.harmony/global-config",
        "description": "list all configured remotes",
        "group": "collaborate",
        "loadAspects": false
      }
    ]
  },
  {
    "name": "rename",
    "aspectId": "teambit.component/renaming",
    "description": "change a component name",
    "group": "component-development",
    "remoteOp": true,
    "skipWorkspace": true
  },
  {
    "name": "reset",
    "aspectId": "teambit.component/snapping",
    "description": "revert local tags and snaps to previous versions",
    "group": "version-control"
  },
  {
    "name": "revert",
    "aspectId": "teambit.component/checkout",
    "description": "replace component files with specified version while preserving current version",
    "group": "version-control"
  },
  {
    "name": "ripple",
    "aspectId": "teambit.cloud/ripple",
    "description": "manage Ripple CI jobs on bit.cloud",
    "group": "collaborate",
    "remoteOp": true,
    "skipWorkspace": true,
    "subCommands": [
      {
        "name": "errors",
        "aspectId": "teambit.cloud/ripple",
        "description": "show build errors for a Ripple CI job (auto-detects current lane, or your last export when on main)",
        "group": "ungrouped",
        "remoteOp": true,
        "skipWorkspace": true
      },
      {
        "name": "list",
        "aspectId": "teambit.cloud/ripple",
        "description": "list recent Ripple CI jobs (filtered by workspace owner by default)",
        "group": "ungrouped",
        "remoteOp": true,
        "skipWorkspace": true
      },
      {
        "name": "log",
        "aspectId": "teambit.cloud/ripple",
        "description": "show job details and component build task summaries (auto-detects current lane, or your last export when on main)",
        "group": "ungrouped",
        "remoteOp": true,
        "skipWorkspace": true
      },
      {
        "name": "retry",
        "aspectId": "teambit.cloud/ripple",
        "description": "retry a failed Ripple CI job (auto-detects current lane when no job-id given)",
        "group": "ungrouped",
        "remoteOp": true,
        "skipWorkspace": true
      },
      {
        "name": "stop",
        "aspectId": "teambit.cloud/ripple",
        "description": "stop a running Ripple CI job (auto-detects current lane when no job-id given)",
        "group": "ungrouped",
        "remoteOp": true,
        "skipWorkspace": true
      }
    ]
  },
  {
    "name": "run",
    "aspectId": "teambit.harmony/application",
    "alias": "c",
    "description": "start an application component locally",
    "group": "run-serve"
  },
  {
    "name": "run-action",
    "aspectId": "teambit.scope/scope",
    "description": "run an action on a remote",
    "group": "advanced",
    "private": true,
    "loadAspects": false
  },
  {
    "name": "schema",
    "aspectId": "teambit.semantics/schema",
    "alias": "api",
    "description": "display component API schema and type definitions",
    "group": "info-analysis",
    "subCommands": [
      {
        "name": "diff",
        "aspectId": "teambit.semantics/schema",
        "description": "show API changes between two versions of a component",
        "group": "info-analysis"
      }
    ]
  },
  {
    "name": "scope",
    "aspectId": "teambit.scope/scope",
    "description": "manage component scope names and assignments",
    "group": "component-config",
    "subCommands": [
      {
        "name": "fork",
        "aspectId": "teambit.scope/scope",
        "description": "fork all components of the original-scope and refactor the source-code to use the new scope name",
        "group": "component-config"
      },
      {
        "name": "rename",
        "aspectId": "teambit.scope/scope",
        "description": "rename the scope name for all components with the specified 'current scope name'. if exported, create new components and delete the original ones",
        "group": "component-config"
      },
      {
        "name": "rename-owner",
        "aspectId": "teambit.scope/scope",
        "description": "Renames the owner part of the scope-name for all components with the specified 'current owner name'",
        "group": "component-config"
      },
      {
        "name": "set",
        "aspectId": "teambit.scope/scope",
        "description": "Sets the scope for specified component/s. If no component is specified, sets the default scope of the workspace",
        "group": "component-config"
      },
      {
        "name": "trust",
        "aspectId": "teambit.scope/scope",
        "description": "manage which scopes are trusted to load aspects (envs, etc.) into the workspace's process",
        "group": "component-config",
        "loadAspects": false
      }
    ]
  },
  {
    "name": "script",
    "aspectId": "teambit.workspace/scripts",
    "description": "run a script defined by the environment",
    "group": "development"
  },
  {
    "name": "search",
    "aspectId": "teambit.component/lister",
    "description": "search for components by keyword in the local workspace and remote bit cloud",
    "group": "info-analysis",
    "remoteOp": true,
    "skipWorkspace": true
  },
  {
    "name": "serve-preview",
    "aspectId": "teambit.preview/preview",
    "description": "serve local preview bundle for components",
    "group": "run-serve",
    "private": true
  },
  {
    "name": "server",
    "aspectId": "teambit.harmony/api-server",
    "description": "communicate with bit cli program via http requests",
    "group": "workspace-setup",
    "private": true
  },
  {
    "name": "snap",
    "aspectId": "teambit.component/snapping",
    "description": "create immutable component snapshots for development versions",
    "group": "version-control"
  },
  {
    "name": "snap-distance",
    "aspectId": "teambit.component/snapping",
    "description": "show common-snap and distance between two given snaps or between local and remote snaps",
    "group": "advanced",
    "private": true
  },
  {
    "name": "start",
    "aspectId": "teambit.ui-foundation/ui",
    "alias": "c",
    "description": "launch the Bit development server",
    "group": "run-serve"
  },
  {
    "name": "stash",
    "aspectId": "teambit.component/stash",
    "description": "temporarily save and restore component changes",
    "group": "version-control",
    "subCommands": [
      {
        "name": "list",
        "aspectId": "teambit.component/stash",
        "description": "list stash",
        "group": "version-control"
      },
      {
        "name": "load",
        "aspectId": "teambit.component/stash",
        "alias": "pop",
        "description": "apply the changes according to the stash. if no stash-id provided, it loads the latest stash",
        "group": "version-control"
      },
      {
        "name": "save",
        "aspectId": "teambit.component/stash",
        "alias": "s",
        "description": "stash modified components",
        "group": "version-control"
      }
    ]
  },
  {
    "name": "tag",
    "aspectId": "teambit.component/snapping",
    "alias": "t",
    "description": "create immutable component snapshots with semantic version tags",
    "group": "version-control",
    "remoteOp": true
  },
  {
    "name": "templates",
    "aspectId": "teambit.generator/generator",
    "description": "list available templates for creating components and workspaces",
    "group": "component-development"
  },
  {
    "name": "test",
    "aspectId": "teambit.defender/tester",
    "alias": "at",
    "description": "run component tests",
    "group": "testing"
  },
  {
    "name": "ui-build",
    "aspectId": "teambit.ui-foundation/ui",
    "alias": "c",
    "description": "build production assets for deployment.",
    "group": "run-serve",
    "private": true
  },
  {
    "name": "undeprecate",
    "aspectId": "teambit.component/deprecation",
    "description": "remove the deprecation status from a component",
    "group": "collaborate",
    "remoteOp": true,
    "skipWorkspace": true
  },
  {
    "name": "uninstall",
    "aspectId": "teambit.workspace/install",
    "alias": "un",
    "description": "remove dependencies from workspace",
    "group": "dependencies"
  },
  {
    "name": "unuse",
    "aspectId": "teambit.workspace/workspace",
    "description": "unset aspects in the workspace config (opposite of \"use\" command)",
    "group": "workspace-setup",
    "private": true,
    "remoteOp": true
  },
  {
    "name": "update",
    "aspectId": "teambit.workspace/install",
    "alias": "up",
    "description": "update workspace dependencies to newer versions",
    "group": "dependencies"
  },
  {
    "name": "use",
    "aspectId": "teambit.workspace/workspace",
    "description": "set aspects in the workspace/scope config to make them loadable by the workspace/scope",
    "group": "workspace-setup",
    "private": true,
    "remoteOp": true
  },
  {
    "name": "validate",
    "aspectId": "teambit.defender/validator",
    "description": "run type-checking, linting, and testing in sequence",
    "group": "testing"
  },
  {
    "name": "watch",
    "aspectId": "teambit.workspace/watcher",
    "description": "watch and compile components on file changes",
    "group": "component-development"
  },
  {
    "name": "whoami",
    "aspectId": "teambit.cloud/cloud",
    "description": "display the currently authenticated Bit Cloud user",
    "group": "auth",
    "skipWorkspace": true
  },
  {
    "name": "ws-config",
    "aspectId": "teambit.workspace/workspace-config-files",
    "alias": "workspace-config",
    "description": "generate IDE configuration files",
    "group": "workspace-tools",
    "subCommands": [
      {
        "name": "clean",
        "aspectId": "teambit.workspace/workspace-config-files",
        "description": "clean (delete) written config files in the workspace. useful for IDEs",
        "group": "workspace-tools"
      },
      {
        "name": "list",
        "aspectId": "teambit.workspace/workspace-config-files",
        "description": "list config writers",
        "group": "workspace-tools"
      },
      {
        "name": "write",
        "aspectId": "teambit.workspace/workspace-config-files",
        "description": "write config files in the workspace. useful for IDEs",
        "group": "workspace-tools"
      }
    ]
  }
];
