// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Generated by scripts/generate-command-index.mjs
// (RFC: ESM Migration with Lazy-Loaded Aspects — slot producer index)
// To regenerate, run: npm run generate-command-index
//
// Map of slot type-parameter name → list of aspect ids whose `*.main.runtime.ts`
// declares a `static slots = [Slot.withType<TYPE>()]` of that type. Built by
// static analysis; the type name is the literal source text inside `<...>`.

export const SLOT_INDEX: Record<string, string[]> = {
  "AddComponentsIssues": [
    "teambit.component/issues"
  ],
  "AddPackagesToLinkSlot": [
    "teambit.dependencies/dependency-resolver"
  ],
  "Application[]": [
    "teambit.harmony/application"
  ],
  "ApplicationType<unknown>[]": [
    "teambit.harmony/application"
  ],
  "BrowserRuntime": [
    "teambit.compilation/bundler"
  ],
  "BuildMethodOverwriteSlot": [
    "teambit.ui-foundation/ui"
  ],
  "BuildTask": [
    "teambit.pipelines/builder"
  ],
  "BundlingStrategy": [
    "teambit.preview/preview"
  ],
  "CapsuleTransferFn": [
    "teambit.component/isolator"
  ],
  "CommandList": [
    "teambit.harmony/cli"
  ],
  "ComponentFactory": [
    "teambit.component/component"
  ],
  "ComponentTemplate[]": [
    "teambit.generator/generator"
  ],
  "DependencyDetector": [
    "teambit.dependencies/dependency-resolver"
  ],
  "DependencyFactory": [
    "teambit.dependencies/dependency-resolver"
  ],
  "DeploymentProvider[]": [
    "teambit.harmony/application"
  ],
  "DevPatterns": [
    "teambit.component/dev-files"
  ],
  "DevServerTransformerSlot": [
    "teambit.compilation/bundler"
  ],
  "Diagnostic[]": [
    "teambit.harmony/diagnostic"
  ],
  "DocProp": [
    "teambit.docs/docs"
  ],
  "DocReader": [
    "teambit.docs/docs"
  ],
  "Environment": [
    "teambit.envs/envs"
  ],
  "EnvJsoncMergeCustomizerRegistry": [
    "teambit.envs/envs"
  ],
  "EnvJsoncResolverRegistry": [
    "teambit.envs/envs"
  ],
  "EnvService<any>": [
    "teambit.envs/envs"
  ],
  "GotEventSlot": [
    "teambit.harmony/ipc-events"
  ],
  "GraphQLServer": [
    "teambit.harmony/graphql"
  ],
  "HarmonyWorker<unknown>": [
    "teambit.harmony/worker"
  ],
  "ImpactRule[]": [
    "teambit.semantics/schema"
  ],
  "MiddlewareManifest[]": [
    "teambit.harmony/express"
  ],
  "OnAspectLoadError": [
    "teambit.harmony/aspect-loader"
  ],
  "OnAspectsResolve": [
    "teambit.workspace/workspace"
  ],
  "OnBeforeExitFn": [
    "teambit.harmony/cli"
  ],
  "OnBitmapChange": [
    "teambit.workspace/workspace"
  ],
  "OnCommandStart": [
    "teambit.harmony/cli"
  ],
  "OnCompAspectReCalc": [
    "teambit.scope/scope"
  ],
  "OnComponentAdd": [
    "teambit.workspace/workspace"
  ],
  "OnComponentChange": [
    "teambit.workspace/workspace"
  ],
  "OnComponentCreateFn": [
    "teambit.generator/generator"
  ],
  "OnComponentLoad": [
    "teambit.workspace/workspace"
  ],
  "OnComponentRemove": [
    "teambit.workspace/workspace"
  ],
  "OnLoadRequireableExtension": [
    "teambit.harmony/aspect-loader"
  ],
  "OnPostDelete": [
    "teambit.scope/scope"
  ],
  "OnPostExport": [
    "teambit.scope/scope"
  ],
  "OnPostObjectRead": [
    "teambit.scope/scope"
  ],
  "OnPostObjectsPersist": [
    "teambit.scope/scope"
  ],
  "OnPostPut": [
    "teambit.scope/scope"
  ],
  "OnPreDevServerCreatedSlot": [
    "teambit.compilation/bundler"
  ],
  "OnPreFetchObjects": [
    "teambit.scope/scope"
  ],
  "OnPreObjectPersist": [
    "teambit.scope/scope"
  ],
  "OnPreSnap": [
    "teambit.component/snapping"
  ],
  "OnPreWatch": [
    "teambit.workspace/watcher"
  ],
  "OnRootAspectAdded": [
    "teambit.workspace/workspace"
  ],
  "OnStart": [
    "teambit.harmony/cli",
    "teambit.ui-foundation/ui"
  ],
  "OnSuccessLogin": [
    "teambit.cloud/cloud"
  ],
  "OnWorkspaceConfigChange": [
    "teambit.workspace/workspace"
  ],
  "PackageJsonProps": [
    "teambit.pkg/pkg"
  ],
  "PackageManager": [
    "teambit.dependencies/dependency-resolver"
  ],
  "Parser": [
    "teambit.semantics/schema"
  ],
  "PluginDefinition[]": [
    "teambit.harmony/aspect-loader"
  ],
  "PostInstallSlot": [
    "teambit.workspace/install"
  ],
  "PostInstallSubscriberList": [
    "teambit.dependencies/dependency-resolver"
  ],
  "PreInstallSlot": [
    "teambit.workspace/install"
  ],
  "PreInstallSubscriberList": [
    "teambit.dependencies/dependency-resolver"
  ],
  "PreLinkSlot": [
    "teambit.workspace/install"
  ],
  "PreStart": [
    "teambit.ui-foundation/ui"
  ],
  "PreviewDefinition": [
    "teambit.preview/preview"
  ],
  "PublicDirOverwriteSlot": [
    "teambit.ui-foundation/ui"
  ],
  "PubSubSlot": [
    "teambit.harmony/graphql"
  ],
  "RegExp": [
    "teambit.dependencies/dependency-resolver"
  ],
  "Route[]": [
    "teambit.component/component",
    "teambit.harmony/express"
  ],
  "Schema": [
    "teambit.harmony/graphql"
  ],
  "SchemaNodeTransformer[]": [
    "teambit.typescript/typescript"
  ],
  "SchemaTransformer[]": [
    "teambit.typescript/typescript"
  ],
  "ShowFragment[]": [
    "teambit.component/component"
  ],
  "StartPlugin": [
    "teambit.ui-foundation/ui"
  ],
  "string": [
    "teambit.harmony/worker"
  ],
  "UIRoot": [
    "teambit.ui-foundation/ui"
  ],
  "VariantPolicyConfigObject": [
    "teambit.dependencies/dependency-resolver"
  ],
  "WorkspacePolicy": [
    "teambit.dependencies/dependency-resolver"
  ],
  "WorkspaceTemplate[]": [
    "teambit.generator/generator"
  ]
};
