FROM node:12.22.0
RUN adduser --disabled-password --gecos '' user
RUN chown -R user /usr/local/
USER user

ENV BVM_GLOBALS_DIR=/tmp/bvm
RUN npm i @teambit/bvm -g
RUN bvm config
RUN bvm upgrade
# RUN bvm link --verbose
ENV PATH=$PATH:/home/user/bin:/tmp/bin
ENV BIT_GLOBALS_DIR=/tmp/bit
RUN bit config set analytics_reporting false
RUN bit config set no_warnings false
RUN bit config set interactive false
RUN bit config set error_reporting true
