import { expect } from 'chai';
import fs from 'fs-extra';
import { tmpdir } from 'os';
import { join } from 'path';
import type { ConfigWriterEntry } from '../config-writer-entry';
import { isUserAuthoredConfigFile } from './extending-config-files';

const BIT_GENERATED_COMMENT = '// bit-generated-typescript-config';

function mockConfigWriter(withIsBitGenerated = true): ConfigWriterEntry {
  const configWriter = {
    id: 'typescript',
    name: 'TypescriptConfigWriter',
    patterns: ['**/tsconfig.json'],
    calcConfigFiles: () => undefined,
    generateExtendingFile: () => undefined,
  } as unknown as ConfigWriterEntry;
  if (withIsBitGenerated) {
    configWriter.isBitGenerated = (filePath: string) =>
      fs.readFileSync(filePath).toString().includes(BIT_GENERATED_COMMENT);
  }
  return configWriter;
}

describe('isUserAuthoredConfigFile()', () => {
  let dir: string;
  before(async () => {
    dir = join(tmpdir(), `bit-ws-config-files-${Date.now()}`);
    await fs.ensureDir(dir);
    await fs.outputFile(join(dir, 'bit-generated.json'), `${BIT_GENERATED_COMMENT}\n{ "extends": "./whatever.json" }`);
    await fs.outputFile(join(dir, 'user-authored.json'), '{ "compilerOptions": { "strict": true } }');
    await fs.ensureDir(join(dir, 'a-directory.json'));
  });
  after(async () => {
    await fs.remove(dir);
  });

  it('should return false when the file does not exist', async () => {
    const result = await isUserAuthoredConfigFile(join(dir, 'does-not-exist.json'), mockConfigWriter());
    expect(result).to.be.false;
  });

  it('should return false when the existing file was generated by bit', async () => {
    const result = await isUserAuthoredConfigFile(join(dir, 'bit-generated.json'), mockConfigWriter());
    expect(result).to.be.false;
  });

  it('should return true when the existing file was not generated by bit', async () => {
    const result = await isUserAuthoredConfigFile(join(dir, 'user-authored.json'), mockConfigWriter());
    expect(result).to.be.true;
  });

  it('should return false when the writer is unable to tell whether the file was generated by bit', async () => {
    const result = await isUserAuthoredConfigFile(join(dir, 'user-authored.json'), mockConfigWriter(false));
    expect(result).to.be.false;
  });

  it('should return false when no config writer was given', async () => {
    const result = await isUserAuthoredConfigFile(join(dir, 'user-authored.json'));
    expect(result).to.be.false;
  });

  it('should return true when the existing file cannot be read', async () => {
    const result = await isUserAuthoredConfigFile(join(dir, 'a-directory.json'), mockConfigWriter());
    expect(result).to.be.true;
  });
});
