import fs from 'fs-extra';

import { AUTO_GENERATED_MSG, AUTO_GENERATED_STAMP } from '../constants';

export type OutputFileParams = {
  filePath: string;
  content: string;
  writeAutoGeneratedMessage?: boolean;
  override?: boolean;
  prefixMessage?: string;
};

export default async function outputFile({
  filePath,
  content,
  writeAutoGeneratedMessage = true,
  override = true,
  prefixMessage,
}: OutputFileParams): Promise<string> {
  if (!override && fs.existsSync(filePath)) {
    const fileContent = fs.readFileSync(filePath).toString();
    if (!fileContent.includes(AUTO_GENERATED_STAMP)) return Promise.resolve(filePath);
  }
  let prefix = writeAutoGeneratedMessage ? AUTO_GENERATED_MSG : '';
  prefix = `${prefix}${prefixMessage}`;
  const data = prefix + content;
  await fs.outputFile(filePath, data);
  return Promise.resolve(filePath);
}
