// @TODO refactor this file to include only exports
import sha1 from './encryption/sha1';
import * as eol from './eol';
import writeFile from './fs-write-file';
import { checksum, checksumFile } from './checksum';
import getWithoutExt from './fs/fs-no-ext';
import getExt from './fs/get-ext';
import isDirEmpty from './fs/is-dir-empty';
import glob from './glob';
import { retrieveIgnoreList } from './ignore/ignore';
import immutableUnshift from './immutable-unshift';
import isBitUrl from './is-bit-url';
import isDir from './is-dir';
import isDirEmptySync from './is-dir-empty-sync';
import isAutoGeneratedFile from './is-file-auto-generated';
import isRelativeImport from './is-relative-import';
import isValidPath from './is-valid-path';
import mapToObject from './map/to-object';
import isNumeric from './number/is-numeric';
import cleanObject from './object-clean';
import objectToStringifiedTupleArray from './object-to-stringified-tuple-array';
import resolveGroupId from './os-resolve-group-id';
import resolveHomePath from './os-resolve-home-path';
import { pathJoinLinux, pathNormalizeToLinux, pathRelativeLinux, pathResolveToLinux } from './path';
import { pathIsInside } from './path-is-inside';
import prependBang from './prepend-bang';
import getLatestVersionNumber from './resolveLatestVersion';
import fromBase64 from './string/from-base64';
import getStringifyArgs from './string/get-stringify-args';
import removeChalkCharacters from './string/remove-chalk-characters';
import stripTrailingChar from './string/strip-trailing-char';
import toBase64 from './string/to-base64';
import toBase64ArrayBuffer from './string/to-base64-array-buffer';
import deflate from './zlib-deflate';
import inflate from './zlib-inflate';

export {
  sha1,
  objectToStringifiedTupleArray,
  resolveGroupId,
  mapToObject,
  removeChalkCharacters,
  getStringifyArgs,
  isNumeric,
  inflate,
  deflate,
  toBase64,
  toBase64ArrayBuffer,
  fromBase64,
  glob,
  checksum,
  checksumFile,
  writeFile,
  cleanObject,
  prependBang,
  isBitUrl,
  isDir,
  resolveHomePath,
  isDirEmpty,
  isDirEmptySync,
  immutableUnshift,
  stripTrailingChar,
  getLatestVersionNumber,
  getWithoutExt,
  getExt,
  pathNormalizeToLinux,
  pathJoinLinux,
  pathRelativeLinux,
  pathResolveToLinux,
  retrieveIgnoreList,
  pathIsInside,
  isValidPath,
  isAutoGeneratedFile,
  eol,
  isRelativeImport,
};
