import { join, resolve } from 'path';

/**
 * # The layout of the bundled distribution, and why it is this one
 *
 * Everything below is shaped by one constraint: the distribution IS the `@teambit/bit` package. It
 * has to survive being published to npm and installed by bvm, while keeping every core aspect
 * importable as `@teambit/<aspect>` from a user's workspace.
 *
 * ```
 * <package root>/                        ← @teambit/bit, and the local out-dir, identically
 * ├── package.json                       ← declares the externals as ordinary dependencies
 * ├── bin/bit                            ← the launcher
 * ├── node_modules/                      ← NOT ours: where a package manager puts the externals
 * └── dist/
 *     ├── <aspect-name>/index.js         ← LOCATOR (see below) - one per core aspect
 *     └── core-aspects/
 *         ├── bundle/bit.app.js          ← the bundle + its on-disk assets and workers
 *         └── node_modules/@teambit/<aspect-name>/   ← the real shim packages
 * ```
 *
 * ## Why the shims live under a *nested* `node_modules`
 *
 * Node resolves a bare `@teambit/workspace` by walking up from the importing file looking for
 * `node_modules`. From `dist/core-aspects/bundle/bit.app.js` that walk reaches
 * `dist/core-aspects/node_modules/@teambit/workspace` before anything else - so
 * `require('@teambit/workspace')` and `require.resolve('@teambit/workspace')` resolve to the shim
 * with **no change to `getAspectDir` or any other runtime code**. That matters more than it sounds:
 * `getAspectDir` is on the hot path of every bit command in every user workspace (`getMainAspect`,
 * `requireAspects`, `workspace-aspects-loader.getAspectDef`), so not touching it is worth a slightly
 * unusual directory.
 *
 * npm strips only the *root* `node_modules` from a tarball; a nested one is published normally
 * (verified with `npm pack --dry-run`). The externals, by contrast, are declared as real
 * dependencies and land in the install root's `node_modules`, which the same upward walk finds one
 * level further out.
 *
 * ## Alternatives considered
 *
 * - **`dist/<aspect>/` as the package itself.** The obvious first choice, since a released
 *   `@teambit/bit` already has those directories. It cannot work: `DependencyLinker.linkCoreAspect`
 *   does `require('<mainAspect>/dist/<name>')` and reads `module.path` off the result, i.e. that
 *   directory is a *locator* that points at the real package, not the package. And the two roles
 *   cannot share one directory - node resolves a directory require through `package.json.main` when
 *   a package.json exists and only falls back to `index.js` when it does not, so adding a
 *   package.json turns the locator into a package and breaks the linker.
 * - **A plain `dist/core-aspects/@teambit/<name>/` (no `node_modules` segment)** plus a new
 *   bundle-aware branch in `getAspectDir`. Publishes just as well, but buys a change to the
 *   most-executed resolution function in the product to avoid one directory name. Rejected.
 * - **Root `node_modules/@teambit/<name>` + `bundleDependencies`** listing all ~107 shims - the only
 *   way npm keeps a root `node_modules`. No source change either, but it makes the package layout
 *   depend on a rarely-used npm feature and a 107-entry list that must track the manifest.
 * - **Publishing ~107 thin packages** that re-export the bundle. Preserves today's resolution
 *   exactly, but is a large amount of registry churn for packages that contain two lines each.
 *
 * ## The locators are still needed
 *
 * `dist/<aspect-name>/index.js` stays, because `linkCoreAspect` looks there *first* and uses it to
 * find what to symlink into a user's `node_modules`. It is generated by this bundler rather than by
 * `@teambit/aspect`'s `CoreExporterTask`, and points at the shim instead of at a published package.
 */
export type BundlePaths = {
  /** where the compiled `@teambit/*` packages are read from (repo root, or a capsule) */
  packagesRoot: string;
  /** the root of the produced distribution - i.e. the package root */
  rootOutDir: string;
  /** `<root>/dist/core-aspects/bundle` - the bundle file plus everything it reads off disk */
  bundleDir: string;
  /** `<root>/dist/core-aspects/node_modules` - parent of the `@teambit/*` shim packages */
  shimsDir: string;
  /** `<root>/dist` - parent of the per-aspect locator directories */
  locatorsDir: string;
  /** basename of the bundle file, e.g. `bit.app.js` */
  appFileName: string;
  /** absolute path of the bundle file */
  appFilePath: string;
  /** where the generated esbuild entry + barrels are written */
  generatedDir: string;
};

export const DEFAULT_OUT_DIR = '/tmp/bit-bundle';
/** relative to the package root; also the value baked into the SEA launcher */
export const BUNDLE_DIR_REL = join('dist', 'core-aspects', 'bundle');
export const SHIMS_DIR_REL = join('dist', 'core-aspects', 'node_modules');
export const APP_FILE_BASE_NAME = 'bit.app';

export function getBundlePaths(packagesRoot: string, outDir = DEFAULT_OUT_DIR): BundlePaths {
  // the bundler spawns child processes with other cwds (npm install, the bundle introspection used
  // for the esm bridges), so a relative out-dir would resolve differently depending on the step.
  const rootOutDir = resolve(packagesRoot, outDir);
  const bundleDir = join(rootOutDir, BUNDLE_DIR_REL);
  const appFileName = `${APP_FILE_BASE_NAME}.js`;
  return {
    packagesRoot,
    rootOutDir,
    bundleDir,
    shimsDir: join(rootOutDir, SHIMS_DIR_REL),
    locatorsDir: join(rootOutDir, 'dist'),
    appFileName,
    appFilePath: join(bundleDir, appFileName),
    // under the source installation's node_modules, so `@teambit/*` resolves from the generated
    // entry with no extra configuration and nothing generated reaches git, tsc or the linter.
    generatedDir: join(packagesRoot, 'node_modules', '.bit-bundle'),
  };
}
