/* eslint-disable no-console */
import fs from 'fs-extra';
import { execFile } from 'child_process';
import { join } from 'path';
import { promisify } from 'util';
import type { BundlePaths } from './config';

const execFileP = promisify(execFile);

/**
 * Envs and user components are ESM: `import { ComponentMap } from '@teambit/component'`.
 *
 * Node can synthesise named exports for a CommonJS module, but only for shapes `cjs-module-lexer`
 * can read statically - and a shim whose whole body is `module.exports = require(bundle).component`
 * is not one of them. So each shim needs an ESM bridge that names its exports explicitly, the same
 * `esm.mjs` convention bit already uses.
 *
 * Those files are hand-written in the repo, which is why they drift (`bit-bundle2` has a commit
 * literally titled "update all esm.mjs files"). Here they are *derived*: the freshly built bundle is
 * loaded in a child process and asked for the real export names, so a bridge can never disagree with
 * what the bundle actually exposes.
 */

const RESERVED = new Set(['default', 'await', 'class', 'const', 'enum', 'export', 'import', 'new', 'super', 'void']);
const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

async function readExportNames(paths: BundlePaths): Promise<Record<string, string[]>> {
  const script = `
    const bundle = require(${JSON.stringify(paths.appFilePath)});
    const out = {};
    for (const key of Object.keys(bundle)) {
      const value = bundle[key];
      if (!value || (typeof value !== 'object' && typeof value !== 'function')) continue;
      out[key] = Object.keys(value);
    }
    process.stdout.write(JSON.stringify(out));
  `;
  const { stdout } = await execFileP(process.execPath, ['-e', script], {
    maxBuffer: 64 * 1024 * 1024,
    cwd: paths.bundleDir,
  });
  return JSON.parse(stdout);
}

function bridgeContent(exportNames: string[]) {
  const usable = exportNames.filter((name) => IDENTIFIER.test(name) && !RESERVED.has(name));
  const lines = [
    '// AUTO-GENERATED by scopes/harmony/bit/bundle - named-export bridge for ESM consumers',
    "import cjsModule from './index.js';",
    '',
    ...usable.map((name) => `export const ${name} = cjsModule.${name};`),
    '',
    'export default cjsModule;',
    '',
  ];
  return lines.join('\n');
}

export async function generateEsmBridges(paths: BundlePaths, exportsByPackage: Record<string, string>) {
  let namesByExport: Record<string, string[]>;
  try {
    namesByExport = await readExportNames(paths);
  } catch (err: any) {
    console.warn(`[bundle] could not introspect the bundle for ESM bridges: ${err.message}`);
    return { generated: 0, skipped: Object.keys(exportsByPackage).length };
  }

  let generated = 0;
  const skipped: string[] = [];
  await Promise.all(
    Object.entries(exportsByPackage).map(async ([packageName, exportName]) => {
      const names = namesByExport[exportName];
      if (!names) {
        skipped.push(packageName);
        return;
      }
      const distDir = join(paths.shimsDir, packageName, 'dist');
      await fs.outputFile(join(distDir, 'esm.mjs'), bridgeContent(names));
      generated += 1;
    })
  );
  if (skipped.length) console.warn(`[bundle] no ESM bridge for: ${skipped.join(', ')}`);
  return { generated, skipped: skipped.length };
}
