import fs from 'fs-extra';
import { join } from 'path';
import type { CoreAspectInfo } from './core-aspects-info';
import { toExportName } from './core-aspects-info';

const HEADER = `// AUTO-GENERATED by scopes/harmony/bit/bundle - do not edit, do not commit.\n`;

export type GeneratedEntry = {
  entryFilePath: string;
  seaEntryFilePath: string;
  /** the export names the bundle exposes, one per shim package */
  exportsByPackage: Record<string, string>;
};

/**
 * writes the esbuild entry point and its two generated barrels into `node_modules/.bit-bundle`.
 *
 * they live under the repo's `node_modules` (rather than in the source tree) for two reasons:
 * 1. `@teambit/*` specifiers resolve from there with no extra esbuild configuration;
 * 2. nothing generated ever reaches git, tsc or the linter.
 */
export async function generateEntry(
  generatedDir: string,
  aspects: CoreAspectInfo[],
  extraPackages: string[]
): Promise<GeneratedEntry> {
  await fs.ensureDir(generatedDir);

  const exportsByPackage: Record<string, string> = {};
  const exportLines = aspects.map((aspect) => {
    exportsByPackage[aspect.packageName] = aspect.exportName;
    return `export * as ${aspect.exportName} from '${aspect.packageName}';`;
  });
  extraPackages.forEach((packageName) => {
    const exportName = toExportName(packageName.replace('@teambit/', ''));
    exportsByPackage[packageName] = exportName;
    exportLines.push(`export * as ${exportName} from '${packageName}';`);
  });

  // side-effect imports: requiring a `*.main.runtime` file is what calls `XAspect.addRuntime(XMain)`.
  // in a non-bundled bit this happens lazily in `requireAspects` by reading `dist/*.main.runtime.js`
  // off disk; a bundle has no such files, so the imports are materialised here at build time.
  const runtimeLines = aspects
    .filter((aspect) => aspect.mainRuntimeImport)
    .map((aspect) => `import '${aspect.mainRuntimeImport}';`);

  const entry = [
    HEADER,
    `import './core-aspects-runtimes';`,
    `export * from './core-aspects-exports';`,
    `export { runBit as runBitApp } from '@teambit/bit/run-bit';`,
    ``,
  ].join('\n');

  await fs.writeFile(join(generatedDir, 'core-aspects-exports.ts'), `${HEADER}${exportLines.join('\n')}\n`);
  await fs.writeFile(join(generatedDir, 'core-aspects-runtimes.ts'), `${HEADER}${runtimeLines.join('\n')}\n`);
  const entryFilePath = join(generatedDir, 'entry.ts');
  await fs.writeFile(entryFilePath, entry);

  // a single executable has no launcher script to call `runBitApp()` - the embedded main script *is*
  // the entry point, so this variant starts the CLI itself.
  const seaEntryFilePath = join(generatedDir, 'sea-entry.ts');
  await fs.writeFile(
    seaEntryFilePath,
    `${HEADER}import { runBitApp } from './entry';\n\n// eslint-disable-next-line @typescript-eslint/no-floating-promises\nrunBitApp();\n`
  );

  return { entryFilePath, seaEntryFilePath, exportsByPackage };
}
