import fs from 'fs-extra';
import globby from 'globby';
import { join, relative } from 'path';
import type { BundlePaths } from './config';
import { resolvePackageDir } from './resolve-package-dir';
import type { CoreAspectInfo } from './core-aspects-info';
import { toExportName } from './core-aspects-info';

/**
 * Emits the two things that keep `@teambit/<aspect>` working without the ~680 real packages.
 * See `config.ts` for the layout and the alternatives that were rejected.
 *
 * 1. **The shim package** - `dist/core-aspects/node_modules/@teambit/<name>/`, a real package whose
 *    entry re-exports that aspect's slice of the single bundle file. Node's module cache guarantees
 *    the bundle is evaluated exactly once however many shims point at it.
 *
 * 2. **The locator** - `dist/<name>/index.js`, exporting `path` to the shim.
 *    `DependencyLinker.linkCoreAspect` requires this directory, reads `module.path`, and symlinks
 *    `resolve(module.path, '..', '..')` into the user's `node_modules/@teambit/<name>` - so the
 *    locator must point at `<shim>/dist/index.js` for those two `..` to land on the shim root.
 *    It must NOT contain a package.json: node would then resolve the directory through `main` and
 *    the linker would read `module.path` off the wrong module.
 *
 *    This is the same file `@teambit/aspect`'s `CoreExporterTask` writes for a non-bundled build,
 *    with the target changed from a published package to the shim. A bundled build therefore has no
 *    use for that task.
 */

type ShimTarget = {
  packageName: string;
  exportName: string;
  /** the core aspect's short name, e.g. `workspace`. absent for non-aspect extras. */
  aspectName?: string;
  /** package.json of the original package, to preserve name/version/componentId */
  sourceDir?: string;
  aspectFileBase?: string;
  mainRuntimeFileBase?: string;
  /** `preview`/`ui`/... runtimes - emitted for discovery only, see `otherRuntimeFileBases` */
  otherRuntimeFileBases?: string[];
};

// the specifier keeps its `.js` under a `dist` layout and drops the extension at the top level (see
// `core-aspects-info`), so strip it here - otherwise the emitted shim is `x.aspect.js.js`. That name
// still *worked*, because `getAspectDef` matches with `.includes('.aspect.js')`, but it is not the
// file name a published package would have.
const basenameOf = (importSpecifier?: string) => importSpecifier?.split('/').pop()?.replace(/\.js$/, '');

function reExport(relativeToBundle: string, exportName: string) {
  return [
    `// AUTO-GENERATED by scopes/harmony/bit/bundle`,
    `Object.defineProperty(exports, '__esModule', { value: true });`,
    `module.exports = require(${JSON.stringify(relativeToBundle)})[${JSON.stringify(exportName)}];`,
    ``,
  ].join('\n');
}

async function readSourcePackageJson(sourceDir?: string): Promise<Record<string, any>> {
  if (!sourceDir) return {};
  try {
    return await fs.readJson(join(sourceDir, 'package.json'));
  } catch {
    return {};
  }
}

/**
 * Copy the aspect's `.d.ts` tree into the shim, so a user's workspace keeps types and autocomplete
 * for `@teambit/<aspect>` even though the implementation is now one opaque bundle file.
 *
 * The declarations are taken verbatim from the package being shimmed rather than regenerated. They
 * are the same ones the published package shipped, which matters for *type identity*: a declaration
 * re-exports its siblings and other `@teambit/*` packages, and those references resolve through the
 * sibling shims - so every aspect sees the same `Component`, `Workspace` and so on. Rolling the
 * declarations up per package (api-extractor style) would break exactly that, and two
 * structurally-identical-but-distinct types are worse for a user than none.
 *
 * The whole tree is copied, not just `index.d.ts`, because those sibling re-exports are relative
 * paths into it. Cost is small - declarations are a fraction of a percent of the distribution.
 *
 * A package with no declarations is normal and not an error: this repo compiles without them unless
 * `bit compile --generate-types` was used, whereas a capsule's packages always carry them.
 */
async function copyTypeDeclarations(sourceDir: string | undefined, shimDistDir: string): Promise<number> {
  if (!sourceDir) return 0;
  const from = join(sourceDir, 'dist');
  // Skip our own output. When building in place, `@teambit/bit`'s source dir *is* the capsule, whose
  // `dist/core-aspects/` now holds every generated shim - so an unfiltered glob copies all 106 shims'
  // declarations into the `bit` shim, recursively and racily (1158 files instead of ~20).
  const files = await globby(['**/*.d.ts', '!core-aspects/**'], { cwd: from, dot: true });
  await Promise.all(
    files.map(async (file) => {
      const target = join(shimDistDir, file);
      await fs.ensureDir(join(target, '..'));
      await fs.copy(join(from, file), target, { dereference: true, overwrite: true });
    })
  );
  return files.length;
}

/**
 * Packages whose real `index.ts` barrel intentionally re-exports a Node-only, build-tooling class as
 * a VALUE - not a bug to fix, a real, load-bearing need (`builder.main.runtime.ts` genuinely
 * `import`s `BundleUiTask` from bare `@teambit/ui` to instantiate it). Their real dist is correctly
 * excluded from `UI_BUNDLING_EXTERNALS`'s default-off installation (D10/D15,
 * `bundle-plan.md` §14/§17 - `@teambit/webpack`'s own `webpack-fallbacks.js` alone needs
 * `assert/`/`buffer/`/`constants-browserify`, part of that ~1.1 GB opt-in group), so a `browser/`
 * copy of their real dist would only ever fail to compile for a browser target - confirmed
 * empirically (2026-09-07): copying all 105 shims' real dist surfaced 57 new errors, most traced to
 * `@teambit/ui`, `@teambit/webpack`, `@teambit/aspect-loader` reaching exactly that externals group,
 * plus a separate handful from `@teambit/harmony` needing `reflect-metadata`/`cleargraph`/etc. - fixed
 * for harmony by vendoring its real runtime dependency closure directly (`copyHarmonyRuntimeDeps`
 * below), not by excluding it here: unlike `@teambit/ui`/`@teambit/webpack`/`@teambit/aspect-loader`,
 * harmony's gap was a handful of small, real, missing npm packages, not an architectural mismatch.
 * Excluding these three here costs nothing bare imports of them didn't already cost before this file
 * existed - they keep today's `require(bit.app.js)[...]` shim behavior, unchanged.
 */
const BROWSER_DIST_EXCLUDED_PACKAGES = new Set(['@teambit/ui', '@teambit/webpack', '@teambit/aspect-loader']);

/**
 * Copy an aspect's REAL compiled `dist/` output into `<shim>/browser/`, verbatim, alongside the
 * existing `dist/` shim - so a browser-target bundler resolving `@teambit/<aspect>`'s **bare
 * specifier** (not one of the specific runtime files `buildUiVendorDll` already covers) gets the
 * actual compiled module instead of `require(bit.app.js)[...]`, which chokes on `bit.app.js`'s own
 * bare `node:*` imports the moment ANYTHING pulls it into a browser compilation (see
 * `bundle-plan/18-findings-log.md`'s 2026-09-07 entries and `26-ui-vendor-dll-design.md` for the
 * repro this fixes).
 *
 * Copied into its own `browser/` directory (not mixed into the existing shim `dist/`) so every
 * *relative* import inside the copied files (`require('./x.aspect')`, `require('./ui/y')`, ...)
 * resolves to another real, copied file - never falls back to a sibling shim. A package with no
 * `index.js` in its real `dist/` (nothing to expose bare), or one of `BROWSER_DIST_EXCLUDED_PACKAGES`
 * above, is skipped; the shim's `dist/index.js` keeps working exactly as it does today either way.
 *
 * `.d.ts`/`.map`/`.mdx` are excluded - types are already served from the shim's own `dist/`
 * (`copyTypeDeclarations`), source maps and docs add real weight (measured, see
 * `bundle-plan/01-goal-and-results.md`) for zero runtime benefit in a browser bundle.
 */
async function copyBrowserDist(
  packageName: string,
  sourceDir: string | undefined,
  browserDir: string
): Promise<number> {
  if (!sourceDir || BROWSER_DIST_EXCLUDED_PACKAGES.has(packageName)) return 0;
  const from = join(sourceDir, 'dist');
  if (!(await fs.pathExists(join(from, 'index.js')))) return 0;
  // same self-reference guard as `copyTypeDeclarations` - building in place, `@teambit/bit`'s own
  // source dir is the capsule whose `dist/core-aspects/` holds every shim already generated.
  const files = await globby(['**/*.js', '**/*.scss', '**/*.css', '**/*.svg', '**/*.json', '!core-aspects/**'], {
    cwd: from,
    dot: true,
  });
  await Promise.all(
    files.map(async (file) => {
      const target = join(browserDir, file);
      await fs.ensureDir(join(target, '..'));
      await fs.copy(join(from, file), target, { dereference: true, overwrite: true });
    })
  );
  return files.length;
}

/**
 * `@teambit/harmony/dist/harmony.js` does a plain top-level `require('reflect-metadata')`, which in
 * turn needs `cleargraph` (`extension-graph.js`), which needs `graphlib`/`lodash`, and so on. Marking
 * these external (`externals.ts`) is the wrong tool even though the header there is right that a
 * separate npm-install *sounds* like the pattern to reach for: `bit.app.js` itself needs
 * `reflect-metadata` at its own top level too (harmony is always loaded), and externals are only
 * installed by a LATER, separate `npm install` step in this same directory - `bit.app.js` would fail
 * to load at all until a consumer completed that second step (verified:
 * `require(bit.app.js)` throws `Cannot find module 'reflect-metadata'` immediately after
 * `npm run bundle` on its own, before that second step runs). `harmony/browser/`'s copy
 * (`copyBrowserDist`) has the exact same problem one level further out - a plain external wouldn't
 * fix that either. Both need every one of these packages already on disk the moment `npm run bundle`
 * finishes, with no further install step - so they are vendored here directly, verbatim, recursively
 * (a dependency's own `dependencies` need the same treatment - `cleargraph` alone pulled in two
 * more), once, at `<shimsDir>/<name>`: node's own upward `node_modules` search from
 * `<shimsDir>/@teambit/harmony/browser/harmony.js` (or from `bit.app.js`'s own bundled
 * `require("reflect-metadata")`, resolved from `<shimsDir>/@teambit/harmony/dist/index.js`) reaches
 * `<shimsDir>` itself as an ancestor, so `<shimsDir>/<name>` satisfies both without any
 * `node_modules`-nesting trick. Every package in this closure is tiny, pure JS, no native/platform
 * variants (verified per-package before adding) - safe to duplicate rather than engineer around.
 */
const HARMONY_RUNTIME_DEPS = ['reflect-metadata', 'cleargraph', 'comment-json', 'user-home'];

/**
 * `resolveFrom` - not `packagesRoot` - because pnpm only symlinks a package's *direct* dependencies
 * into a flat, repo-root `node_modules`; `cleargraph` (harmony's dependency, not the repo's) lives
 * only inside harmony's own per-package store dir (`.pnpm/@teambit+harmony@.../node_modules/`), and
 * `cleargraph`'s own dependencies (`graphlib`, `lodash`) likewise only inside *its* per-package dir.
 * Node's own resolution would look in exactly this place first too - each level recurses from the
 * dir it just found, the same as a real `require()` chain would.
 */
async function copyPackageWithDeps(
  packageName: string,
  resolveFrom: string,
  shimsDir: string,
  copied: Set<string>
): Promise<void> {
  if (copied.has(packageName)) return;
  copied.add(packageName);
  const sourceDir = resolvePackageDir(resolveFrom, packageName);
  if (!sourceDir) {
    // eslint-disable-next-line no-console
    console.warn(
      `[bundle] "${packageName}" not resolvable from ${resolveFrom} - harmony's runtime deps may be incomplete`
    );
    return;
  }
  await fs.copy(sourceDir, join(shimsDir, packageName), { dereference: true, overwrite: true });
  const { dependencies = {} } = await fs.readJson(join(sourceDir, 'package.json')).catch(() => ({}) as any);
  await Promise.all(Object.keys(dependencies).map((dep) => copyPackageWithDeps(dep, sourceDir, shimsDir, copied)));
}

async function copyHarmonyRuntimeDeps(shimsDir: string, harmonyDir: string): Promise<string[]> {
  const copied = new Set<string>();
  await Promise.all(HARMONY_RUNTIME_DEPS.map((name) => copyPackageWithDeps(name, harmonyDir, shimsDir, copied)));
  return [...copied];
}

/**
 * Copy an aspect's `artifacts/` tree into the shim - today that means the pre-built UI and preview
 * bundles produced by `BundleUI` / `PreBundlePreview`.
 *
 * These are not an optimisation, they are what makes `bit start` possible at all in a bundled bit.
 * The alternative is the runtime rspack build, which resolves its loaders and aliases with
 * `require.resolve('<pkg>')` and therefore needs the whole UI dependency tree on disk - measured at
 * +1.1 GB. Serving the pre-built bundle needs no bundler: it is `express.static` for the UI, and a
 * generated one-line entry that imports the pre-bundle for the preview.
 *
 * `getAspectArtifactDir` looks for them at the shim root, which is what a bare
 * `require.resolve('@teambit/ui')` resolves to from inside the bundle.
 */
async function copyShippedArtifacts(sourceDir: string | undefined, shimDir: string): Promise<number> {
  if (!sourceDir) return 0;
  const files = await globby(['artifacts/**'], { cwd: sourceDir, dot: true });
  await Promise.all(
    files.map(async (file) => {
      const target = join(shimDir, file);
      await fs.ensureDir(join(target, '..'));
      await fs.copy(join(sourceDir, file), target, { dereference: true, overwrite: true });
    })
  );
  return files.length;
}

/**
 * `linkCoreAspect` computes the package root as `resolve(module.path, '..', '..')`, so the locator
 * must name a file exactly two levels below the shim root - `<shim>/dist/index.js`.
 */
function locatorContent(fromLocatorToShimMain: string) {
  return [
    `// AUTO-GENERATED by @teambit/harmony.modules.cli-bundler`,
    `// consumed by DependencyLinker.linkCoreAspect, which reads \`path\` and links its grandparent.`,
    `Object.defineProperty(exports, '__esModule', { value: true });`,
    `module.exports.path = require.resolve(${JSON.stringify(fromLocatorToShimMain)});`,
    ``,
  ].join('\n');
}

async function generateOne(paths: BundlePaths, target: ShimTarget) {
  const pkgDir = join(paths.shimsDir, target.packageName);
  const distDir = join(pkgDir, 'dist');
  await fs.ensureDir(distDir);

  const fromPkgDir = relative(pkgDir, paths.appFilePath).split('\\').join('/');
  const fromDistDir = relative(distDir, paths.appFilePath).split('\\').join('/');

  await fs.writeFile(join(pkgDir, 'index.js'), reExport(fromPkgDir, target.exportName));
  await fs.writeFile(join(distDir, 'index.js'), reExport(fromDistDir, target.exportName));

  // `getAspectDef` (aspect-loader) discovers aspects by globbing `<pkg>/dist` for `*.aspect.js` and
  // `*.<runtime>.runtime.js`. Emitting the same file names - re-exporting the bundle - keeps that
  // discovery working without teaching the runtime about bundles.
  if (target.aspectFileBase) {
    await fs.writeFile(join(distDir, `${target.aspectFileBase}.js`), reExport(fromDistDir, target.exportName));
  }
  if (target.mainRuntimeFileBase) {
    await fs.writeFile(join(distDir, `${target.mainRuntimeFileBase}.js`), reExport(fromDistDir, target.exportName));
  }

  // The non-main runtimes (`preview`, `ui`, ...) exist purely so `getAspectDef(id, runtime)` can
  // still find them: it globs `<pkg>/dist` for `*.<runtime>.runtime.js`, and an aspect with no match
  // is dropped from `uiRoot.resolveAspects(runtime)`. That list is what the pre-bundle `.hash` is
  // computed over, so without these files a bundled bit hashes an empty list and can never match a
  // shipped pre-bundle. Their *contents* are never used: only the main runtime runs in the CLI
  // process, and the browser code was pre-bundled at build time into `artifacts/`.
  await Promise.all(
    (target.otherRuntimeFileBases || []).map((base) =>
      fs.writeFile(join(distDir, `${base}.js`), reExport(fromDistDir, target.exportName))
    )
  );

  const original = await readSourcePackageJson(target.sourceDir);
  const typesCopied = await copyTypeDeclarations(target.sourceDir, distDir);
  const artifactsCopied = await copyShippedArtifacts(target.sourceDir, pkgDir);
  const browserDir = join(pkgDir, 'browser');
  const browserFilesCopied = await copyBrowserDist(target.packageName, target.sourceDir, browserDir);
  const hasTypes = typesCopied > 0 && (await fs.pathExists(join(distDir, 'index.d.ts')));
  const hasBrowserDist = browserFilesCopied > 0 && (await fs.pathExists(join(browserDir, 'index.js')));

  const packageJson: Record<string, any> = {
    name: target.packageName,
    version: original.version || '0.0.0',
    componentId: original.componentId,
    main: 'dist/index.js',
    // point at the copied declarations. the original map's `types` entries point at `.ts` *sources*
    // (`"types": "./index.ts"`, `"./dist/*": { "types": "./*.ts" }`), which a shim does not have -
    // inheriting them would leave every import untyped.
    ...(hasTypes ? { types: 'dist/index.d.ts' } : {}),
    // the bundle carries every dependency; declaring them would make `npm i` re-download the world.
    dependencies: {},
    exports: {
      '.': {
        // `types` must come first - node/TS pick the first matching condition
        ...(hasTypes ? { types: './dist/index.d.ts' } : {}),
        // a browser-target bundler (webpack/rspack `target: 'web'`) tries `browser` before
        // `default` - see `copyBrowserDist`'s own comment for why this exists at all. `node` stays
        // pinned to the shim: nothing about the *Node* CLI process's own resolution changes.
        ...(hasBrowserDist ? { browser: './browser/index.js' } : {}),
        // `generate-esm-bridges` derives dist/esm.mjs from the built bundle
        node: { require: './dist/index.js', import: './dist/esm.mjs' },
        default: './dist/index.js',
      },
      './dist/*': './dist/*',
      './*': './*',
    },
    license: original.license || 'Apache-2.0',
    _bitBundleShim: true,
  };
  await fs.writeJson(join(pkgDir, 'package.json'), packageJson, { spaces: 2 });

  // the locator, only for real aspects - `harmony` and friends are not linked by aspect id
  if (target.aspectName) {
    const locatorDir = join(paths.locatorsDir, target.aspectName);
    await fs.ensureDir(locatorDir);
    const rel = relative(locatorDir, join(distDir, 'index.js')).split('\\').join('/');
    await fs.writeFile(join(locatorDir, 'index.js'), locatorContent(rel.startsWith('.') ? rel : `./${rel}`));
  }
  return { typesCopied, artifactsCopied, browserFilesCopied: hasBrowserDist ? browserFilesCopied : 0 };
}

export async function generateShimPackages(paths: BundlePaths, aspects: CoreAspectInfo[], extraPackages: string[]) {
  const targets: ShimTarget[] = aspects.map((aspect) => ({
    packageName: aspect.packageName,
    exportName: aspect.exportName,
    aspectName: aspect.name,
    sourceDir: aspect.dir,
    aspectFileBase: basenameOf(aspect.aspectImport),
    mainRuntimeFileBase: basenameOf(aspect.mainRuntimeImport),
    otherRuntimeFileBases: aspect.otherRuntimeFileBases,
  }));
  extraPackages.forEach((packageName) => {
    targets.push({
      packageName,
      exportName: toExportName(packageName.replace('@teambit/', '')),
      // extras are shimmed like aspects and deserve types like aspects - `@teambit/harmony` is
      // imported directly by user code, so leaving it untyped would be an odd hole.
      sourceDir: resolvePackageDir(paths.packagesRoot, packageName),
    });
  });
  const results = await Promise.all(targets.map((target) => generateOne(paths, target)));
  const typeFiles = results.reduce((acc, r) => acc + r.typesCopied, 0);
  const withTypes = results.filter((r) => r.typesCopied).length;
  const artifactFiles = results.reduce((acc, r) => acc + r.artifactsCopied, 0);
  const browserDistFiles = results.reduce((acc, r) => acc + r.browserFilesCopied, 0);
  const withBrowserDist = results.filter((r) => r.browserFilesCopied).length;
  const harmonyDir = resolvePackageDir(paths.packagesRoot, '@teambit/harmony');
  const harmonyDepsCopied = harmonyDir ? await copyHarmonyRuntimeDeps(paths.shimsDir, harmonyDir) : [];
  // eslint-disable-next-line no-console
  console.log(
    harmonyDir
      ? `[bundle] harmony runtime deps vendored: ${harmonyDepsCopied.join(', ')}`
      : '[bundle] "@teambit/harmony" not resolvable - skipping its vendored runtime deps'
  );
  // types are optional, but their absence is worth saying out loud: it is the difference between a
  // user's workspace getting autocomplete for `@teambit/*` and getting `any`. In this repo it means
  // the components were compiled without `bit compile --generate-types`.
  // eslint-disable-next-line no-console
  console.log(
    `[bundle] type declarations: ${typeFiles} files across ${withTypes}/${targets.length} shims` +
      (withTypes ? '' : ' - the distribution will have no types (compile with --generate-types)')
  );
  // an absent pre-bundle is not a cosmetic gap: without it `bit start` falls back to the runtime
  // rspack build, which needs the UI dependency tree the bundle exists to avoid shipping.
  // eslint-disable-next-line no-console
  console.log(
    artifactFiles
      ? `[bundle] shipped artifacts: ${artifactFiles} files (pre-built UI/preview bundles)`
      : `[bundle] shipped artifacts: none - "bit start" will try to build the UI at runtime. run the ` +
          `BundleUI and PreBundlePreview build tasks so @teambit/ui and @teambit/preview carry artifacts/.`
  );
  // see `copyBrowserDist`'s own comment: without this, ANY browser-target bundler resolving a core
  // aspect's bare specifier (rather than one of the specific runtime files the vendor DLL covers)
  // falls into `require(bit.app.js)[...]`, which cannot compile for a browser target at all.
  // eslint-disable-next-line no-console
  console.log(`[bundle] browser dist: ${browserDistFiles} files across ${withBrowserDist}/${targets.length} shims`);
  return {
    packageNames: targets.map((t) => t.packageName),
    typeFiles,
    shimsWithTypes: withTypes,
    artifactFiles,
    browserDistFiles,
    shimsWithBrowserDist: withBrowserDist,
  };
}
