import fs from 'fs-extra';
import { join, relative } from 'path';
import type { BundlePaths } from './config';
import type { CoreAspectInfo } from './core-aspects-info';
import { toExportName } from './core-aspects-info';

/**
 * Emits the two things that keep `@teambit/<aspect>` working without the ~680 real packages.
 * See `config.ts` for the layout and the alternatives that were rejected.
 *
 * 1. **The shim package** - `dist/core-aspects/node_modules/@teambit/<name>/`, a real package whose
 *    entry re-exports that aspect's slice of the single bundle file. Node's module cache guarantees
 *    the bundle is evaluated exactly once however many shims point at it.
 *
 * 2. **The locator** - `dist/<name>/index.js`, exporting `path` to the shim.
 *    `DependencyLinker.linkCoreAspect` requires this directory, reads `module.path`, and symlinks
 *    `resolve(module.path, '..', '..')` into the user's `node_modules/@teambit/<name>` - so the
 *    locator must point at `<shim>/dist/index.js` for those two `..` to land on the shim root.
 *    It must NOT contain a package.json: node would then resolve the directory through `main` and
 *    the linker would read `module.path` off the wrong module.
 *
 *    This is the same file `@teambit/aspect`'s `CoreExporterTask` writes for a non-bundled build,
 *    with the target changed from a published package to the shim. A bundled build therefore has no
 *    use for that task.
 */

type ShimTarget = {
  packageName: string;
  exportName: string;
  /** the core aspect's short name, e.g. `workspace`. absent for non-aspect extras. */
  aspectName?: string;
  /** package.json of the original package, to preserve name/version/componentId */
  sourceDir?: string;
  aspectFileBase?: string;
  mainRuntimeFileBase?: string;
};

const basenameOf = (importSpecifier?: string) => importSpecifier?.split('/').pop();

function reExport(relativeToBundle: string, exportName: string) {
  return [
    `// AUTO-GENERATED by scopes/harmony/bit/bundle`,
    `Object.defineProperty(exports, '__esModule', { value: true });`,
    `module.exports = require(${JSON.stringify(relativeToBundle)})[${JSON.stringify(exportName)}];`,
    ``,
  ].join('\n');
}

async function readSourcePackageJson(sourceDir?: string): Promise<Record<string, any>> {
  if (!sourceDir) return {};
  try {
    return await fs.readJson(join(sourceDir, 'package.json'));
  } catch {
    return {};
  }
}

/**
 * `linkCoreAspect` computes the package root as `resolve(module.path, '..', '..')`, so the locator
 * must name a file exactly two levels below the shim root - `<shim>/dist/index.js`.
 */
function locatorContent(fromLocatorToShimMain: string) {
  return [
    `// AUTO-GENERATED by @teambit/harmony.modules.cli-bundler`,
    `// consumed by DependencyLinker.linkCoreAspect, which reads \`path\` and links its grandparent.`,
    `Object.defineProperty(exports, '__esModule', { value: true });`,
    `module.exports.path = require.resolve(${JSON.stringify(fromLocatorToShimMain)});`,
    ``,
  ].join('\n');
}

async function generateOne(paths: BundlePaths, target: ShimTarget) {
  const pkgDir = join(paths.shimsDir, target.packageName);
  const distDir = join(pkgDir, 'dist');
  await fs.ensureDir(distDir);

  const fromPkgDir = relative(pkgDir, paths.appFilePath).split('\\').join('/');
  const fromDistDir = relative(distDir, paths.appFilePath).split('\\').join('/');

  await fs.writeFile(join(pkgDir, 'index.js'), reExport(fromPkgDir, target.exportName));
  await fs.writeFile(join(distDir, 'index.js'), reExport(fromDistDir, target.exportName));

  // `getAspectDef` (aspect-loader) discovers aspects by globbing `<pkg>/dist` for `*.aspect.js` and
  // `*.<runtime>.runtime.js`. Emitting the same file names - re-exporting the bundle - keeps that
  // discovery working without teaching the runtime about bundles.
  if (target.aspectFileBase) {
    await fs.writeFile(join(distDir, `${target.aspectFileBase}.js`), reExport(fromDistDir, target.exportName));
  }
  if (target.mainRuntimeFileBase) {
    await fs.writeFile(join(distDir, `${target.mainRuntimeFileBase}.js`), reExport(fromDistDir, target.exportName));
  }

  const original = await readSourcePackageJson(target.sourceDir);
  const packageJson: Record<string, any> = {
    name: target.packageName,
    version: original.version || '0.0.0',
    componentId: original.componentId,
    main: 'dist/index.js',
    // the bundle carries every dependency; declaring them would make `npm i` re-download the world.
    dependencies: {},
    exports: {
      '.': {
        // `generate-esm-bridges` derives dist/esm.mjs from the built bundle
        node: { require: './dist/index.js', import: './dist/esm.mjs' },
        default: './dist/index.js',
      },
      './dist/*': './dist/*',
      './*': './*',
    },
    license: original.license || 'Apache-2.0',
    _bitBundleShim: true,
  };
  await fs.writeJson(join(pkgDir, 'package.json'), packageJson, { spaces: 2 });

  // the locator, only for real aspects - `harmony` and friends are not linked by aspect id
  if (target.aspectName) {
    const locatorDir = join(paths.locatorsDir, target.aspectName);
    await fs.ensureDir(locatorDir);
    const rel = relative(locatorDir, join(distDir, 'index.js')).split('\\').join('/');
    await fs.writeFile(join(locatorDir, 'index.js'), locatorContent(rel.startsWith('.') ? rel : `./${rel}`));
  }
}

export async function generateShimPackages(paths: BundlePaths, aspects: CoreAspectInfo[], extraPackages: string[]) {
  const targets: ShimTarget[] = aspects.map((aspect) => ({
    packageName: aspect.packageName,
    exportName: aspect.exportName,
    aspectName: aspect.name,
    sourceDir: aspect.dir,
    aspectFileBase: basenameOf(aspect.aspectImport),
    mainRuntimeFileBase: basenameOf(aspect.mainRuntimeImport),
  }));
  extraPackages.forEach((packageName) => {
    targets.push({ packageName, exportName: toExportName(packageName.replace('@teambit/', '')) });
  });
  await Promise.all(targets.map((target) => generateOne(paths, target)));
  return targets.map((t) => t.packageName);
}
