import fs from 'fs-extra';
import { join, relative } from 'path';
import type { BundlePaths } from './config';
import type { CoreAspectInfo } from './core-aspects-info';
import { EXTRA_PACKAGES, toExportName } from './core-aspects-info';

/**
 * Every core aspect must still be importable as `@teambit/<name>` from a user's workspace - that is
 * what `DependencyLinker.linkCoreAspect` symlinks into `node_modules/@teambit/*` on `bit install`,
 * and what user code and envs `require`.
 *
 * So for each one we emit a *shim package*: a real directory with a real package.json whose entry
 * point re-exports that aspect's slice of the single bundle file. Node's module cache guarantees
 * the bundle is evaluated exactly once no matter how many shims point at it.
 *
 *   <out>/node_modules/@teambit/workspace/index.js
 *     → module.exports = require('../../../bundle/bit.app.js').workspace
 */

type ShimTarget = {
  packageName: string;
  exportName: string;
  /** package.json of the original package, to preserve name/version/componentId */
  sourceDir?: string;
  aspectFileBase?: string;
  mainRuntimeFileBase?: string;
};

const basenameOf = (importSpecifier?: string) => importSpecifier?.split('/').pop();

function reExport(relativeToBundle: string, exportName: string) {
  return [
    `// AUTO-GENERATED by scopes/harmony/bit/bundle`,
    `Object.defineProperty(exports, '__esModule', { value: true });`,
    `module.exports = require(${JSON.stringify(relativeToBundle)})[${JSON.stringify(exportName)}];`,
    ``,
  ].join('\n');
}

async function readSourcePackageJson(sourceDir?: string): Promise<Record<string, any>> {
  if (!sourceDir) return {};
  try {
    return await fs.readJson(join(sourceDir, 'package.json'));
  } catch {
    return {};
  }
}

async function generateOne(paths: BundlePaths, target: ShimTarget) {
  const pkgDir = join(paths.rootOutDir, 'node_modules', target.packageName);
  const distDir = join(pkgDir, 'dist');
  await fs.ensureDir(distDir);

  const fromPkgDir = relative(pkgDir, paths.appFilePath).split('\\').join('/');
  const fromDistDir = relative(distDir, paths.appFilePath).split('\\').join('/');

  await fs.writeFile(join(pkgDir, 'index.js'), reExport(fromPkgDir, target.exportName));
  await fs.writeFile(join(distDir, 'index.js'), reExport(fromDistDir, target.exportName));

  // `getAspectDef` (aspect-loader) discovers aspects by globbing `<pkg>/dist` for `*.aspect.js` and
  // `*.<runtime>.runtime.js`. Emitting the same file names - re-exporting the bundle - keeps that
  // discovery working without teaching the runtime about bundles.
  if (target.aspectFileBase) {
    await fs.writeFile(join(distDir, `${target.aspectFileBase}.js`), reExport(fromDistDir, target.exportName));
  }
  if (target.mainRuntimeFileBase) {
    await fs.writeFile(join(distDir, `${target.mainRuntimeFileBase}.js`), reExport(fromDistDir, target.exportName));
  }

  const original = await readSourcePackageJson(target.sourceDir);
  const packageJson: Record<string, any> = {
    name: target.packageName,
    version: original.version || '0.0.0',
    componentId: original.componentId,
    main: 'dist/index.js',
    // the bundle carries every dependency; declaring them would make `npm i` re-download the world.
    dependencies: {},
    exports: {
      '.': {
        // `generate-esm-bridges` derives dist/esm.mjs from the built bundle
        node: { require: './dist/index.js', import: './dist/esm.mjs' },
        default: './dist/index.js',
      },
      './dist/*': './dist/*',
      './*': './*',
    },
    license: original.license || 'Apache-2.0',
    _bitBundleShim: true,
  };
  // `@teambit/bit` is what bvm (and `npm i -g`) installs, so it carries the executable
  if (target.packageName === '@teambit/bit') packageJson.bin = { bit: './bin/bit' };
  await fs.writeJson(join(pkgDir, 'package.json'), packageJson, { spaces: 2 });
}

export async function generateShimPackages(paths: BundlePaths, aspects: CoreAspectInfo[]) {
  const targets: ShimTarget[] = aspects.map((aspect) => ({
    packageName: aspect.packageName,
    exportName: aspect.exportName,
    sourceDir: aspect.dir,
    aspectFileBase: basenameOf(aspect.aspectImport),
    mainRuntimeFileBase: basenameOf(aspect.mainRuntimeImport),
  }));
  EXTRA_PACKAGES.forEach((packageName) => {
    targets.push({ packageName, exportName: toExportName(packageName.replace('@teambit/', '')) });
  });
  await Promise.all(targets.map((target) => generateOne(paths, target)));
  return targets.map((t) => t.packageName);
}
