import { getConsumerInfo } from '@teambit/legacy/dist/consumer';
import camelcase from 'camelcase';
import { getCoreAspectName, getCoreAspectPackageName } from '@teambit/aspect-loader';
import fs from 'fs-extra';
import { join } from 'path';

import { coreAspectsIds } from '../core-aspects-ids';

let wsRootDir: string;

async function loadWsRootDir() {
  const consumerInfo = await getConsumerInfo(process.cwd());
  if (!consumerInfo) throw new Error('unable to find consumer');
  wsRootDir = consumerInfo.path;
  return consumerInfo.path;
}

export async function generateCoreAspectsModules(bundleDir: string, appName: string) {
  await loadWsRootDir();
  const generateOneAspectP = coreAspectsIds.map((id) => {
    const name = getCoreAspectName(id);
    const packageName = getCoreAspectPackageName(id);
    return handleOneAspect(bundleDir, name, packageName, appName);
  });
  generateOneAspectP.push(handleOneAspect(bundleDir, 'legacy', '@teambit/legacy', appName));
  generateOneAspectP.push(handleOneAspect(bundleDir, 'harmony', '@teambit/harmony', appName));
  return Promise.all(generateOneAspectP);
}

async function handleOneAspect(bundleDir: string, name: string, packageName: string, appName: string) {
  const dirPath = join(bundleDir, 'node_modules', packageName);
  await fs.ensureDir(dirPath);
  await generateIndexFile(dirPath, name, appName);
  await copyPackageJson(dirPath, packageName);
}

async function generateIndexFile(dirPath: string, name: string, appName: string) {
  const indexFilePath = join(dirPath, 'index.js');
  const indexFileContent = getIndexContent(name, appName);
  return fs.outputFile(indexFilePath, indexFileContent);
}

async function copyPackageJson(dirPath: string, packageName: string) {
  const packageJsonPath = join(wsRootDir, 'node_modules', packageName, 'package.json');
  const targetPath = join(dirPath, 'package.json');
  return fs.copyFile(packageJsonPath, targetPath);
}

function getIndexContent(name: string, appName: string) {
  const camelName = camelcase(name);
  return `
// This file is auto generated by generate-core-aspects-modules.ts
Object.defineProperty(exports, "__esModule", { value: true });
const { ${camelName} } = require("../../${appName}");
module.exports = ${camelName};
`;
}
