// eslint-disable-next-line import/no-unresolved
import cjsModule from './constants.js';

// Export all named exports
export const {
  ACCEPTABLE_NPM_VERSIONS,
  ANGULAR_BIT_ENTRY_POINT_FILE,
  ANGULAR_PACKAGE_IDENTIFIER,
  AUTO_GENERATED_MSG,
  AUTO_GENERATED_STAMP,
  AUTO_SNAPPED_MSG,
  BASE_COMMUNITY_DOMAIN,
  BASE_DOCS_DOMAIN,
  BASE_LEGACY_DOCS_DOMAIN,
  BASE_WEB_DOMAIN,
  BITMAP_PREFIX_MESSAGE,
  BITS_DIRNAME,
  BIT_CACHE_DIRNAME,
  BIT_GIT_DIR,
  BIT_HIDDEN_DIR,
  BIT_JSON,
  BIT_MAP,
  BIT_REGISTRY,
  BIT_ROOTS_DIR,
  BIT_SOURCES_DIRNAME,
  BIT_TMP_DIRNAME,
  BIT_USAGE,
  BIT_WORKSPACE_TMP_DIRNAME,
  BuildStatus,
  CACHE_GLOBALS_ENV,
  CACHE_ROOT,
  CENTRAL_BIT_HUB_NAME,
  CENTRAL_BIT_HUB_URL,
  CENTRAL_BIT_HUB_URL_IMPORTER,
  CENTRAL_BIT_HUB_URL_IMPORTER_V2,
  GLOBAL_CONFIG,
  GLOBAL_LOGS,
  // Add other constants as needed...
} = cjsModule;

export default cjsModule;